framework/components/ABreadcrumb/ABreadcrumb.js
framework/components/ABreadcrumb/ABreadcrumb.mdx
framework/components/ABreadcrumb/ABreadcrumb.scss

#65 - add arrow for single level breadcrumb

---

framework/components/ASimpleTable/ASimpleTable.scss

#79 - adjust font sizes for table

---

framework/components/AInputBase/AInputBase.js
framework/components/AInputBase/AInputBase.mdx
framework/components/AInputBase/AInputBase.scss
framework/components/ATextInput/ATextInput.mdx

#80 - add small/medium/large props to AInputBase

---

framework/components/AList/AList.scss
framework/components/AList/AListItem.js
framework/components/AMenu/AMenu.mdx

Add disabled state to list item

---

framework/components/AButton/AButton.mdx
framework/styles/theme/dusk.scss

Adjust <a> tag colors in dark theme

---

framework/components/AToaster/AToaster.scss

Flip ordering of toasts in display

---

framework/components/AApp/base/links.scss

#107 - sync <a> to design

---

framework/components/AStepper/AStep.js
framework/components/AStepper/AStepper.mdx
framework/components/AStepper/AStepper.scss
framework/styles/theme/default.scss
framework/styles/theme/dusk.scss
framework/styles/utilities/palette.scss

Resolves #100 
Note that the colors won't exactly line up since there is usage of two different color token sets in the design. Spacing, fonts and margins are also not 100%, but have been adjusted for a hopefully safe compromise between not breaking existing usage and getting somewhat closer to magnetic design.

More magnetic sync for AStepper

---

framework/components/ASkeleton/ASkeleton.js
framework/components/ASkeleton/ASkeleton.mdx
framework/components/ASkeleton/ASkeleton.scss
framework/components/ASkeleton/ASkeletonBlock.js
framework/components/ASkeleton/ASkeletonHeader.js
framework/components/ASkeleton/ASkeletonText.js
framework/components/ASkeleton/index.js
framework/index.js
framework/styles/theme/default.scss
framework/styles/theme/dusk.scss
framework/styles/utilities/index.scss
framework/styles/utilities/keyframes.scss

ASkeleton component

---

framework/components/APagination/APagination.js
framework/components/APagination/APagination.mdx
framework/components/APagination/APagination.scss

Resolves #113 
Adding two props on `APagination`:
- showFirstLastButtons: PropTypes.bool,
- showSetPageInput: PropTypes.bool

#113 - add customization props to APagination

---

framework/components/ADataTable/ADataTable.scss
framework/components/ASimpleTable/ASimpleTable.scss
framework/styles/theme/default.scss
framework/styles/theme/dusk.scss

#123 - match table cell border color to magnetic

---

framework/components/APagination/APagination.js
framework/components/APagination/APagination.scss

#124 - change button styles for first/last/next/prev in APagination

---

framework/components/AEmptyState/AEmptyState.js
framework/components/AEmptyState/AEmptyState.mdx
framework/components/AEmptyState/AEmptyState.scss
svg/EmptyBackground.svg

#128 - add size variants for AEmptyState

---

framework/styles/utilities/variables.scss

#118 - check for sharp sans for headers, then fallback to normal font family

---

framework/components/AModal/AModal.js

#133 - check target in onClickOutside for AModal

---

framework/components/AAlert/AAlert.scss

Resolves #157 
- Removes left padding on the dismiss icon
- Adds right padding to the message

#157 - adjust padding for AAlert message

---

framework/styles/utilities/variables.scss

#134 - adjust headings line height

---

framework/components/AAccordion/AAccordion.scss

#135 - adjust body padding for AAccordion

---

framework/styles/theme/default.scss

#146 - adjust color of chevron (icon fill) for AInputBase

---

framework/components/AEmptyState/AEmptyState.scss
framework/styles/theme/default.scss
framework/styles/theme/dusk.scss

#160 - update AEmptyState message color

---

framework/components/AApp/base/color-helpers.scss
framework/components/ADrawer/ADrawer.mdx
framework/styles/theme/dusk.scss
framework/styles/utilities/palette.scss

Bug fix and feature.
* The background color for `ADrawer` in dusk theme is incorrect
* There are no helper classes for Magnetic colors
* Updates the background color of the `ADrawer` in dusk theme
* Adds the Magnetic colors to the helper classes in Magna React.
No

feat: add magnetic colors to helper classes and update drawer dusk bg

---

framework/components/ADataTable/ADataTable.js
framework/components/ADataTable/ADataTable.scss
framework/components/ASimpleTable/ASimpleTable.scss
framework/styles/theme/default.scss
framework/styles/theme/dusk.scss

#122 - add focus/hover state to data table sort headers

---

framework/components/AInputBase/AInputBase.scss

#166 - move validation state css below readOnly

---

framework/components/ABreadcrumb/ABreadcrumb.js
framework/components/ABreadcrumb/ABreadcrumb.mdx

#163 - make single level breadcrum arrow clickable

---

framework/components/AInputBase/AInputBase.scss

#169 - focus box-shadow validation state

---

framework/components/AHint/AHint.js
framework/components/AHint/AHint.scss

#170 - use AAlert in AHint

---

framework/components/AInputBase/AInputBase.scss
framework/components/AList/AList.js
framework/components/AList/AList.scss
framework/components/ASelect/ASelect.js
framework/components/ASelect/ASelect.mdx
framework/styles/utilities/variables.scss

#168 - add medium variant for ASelect

---

framework/components/ADataTable/ADataTable.scss
framework/styles/theme/default.scss
framework/styles/theme/dusk.scss

#182 - update header hover/focus state

---

framework/components/AButton/AButton.js
framework/components/AButton/AButton.mdx
framework/components/AButton/AButton.scss
framework/components/AButtonGroup/AButtonGroup.js
framework/components/AButtonGroup/AButtonGroup.scss
framework/styles/utilities/mixins.scss

#189 Add small button variant

---

framework/components/AModal/AModal.scss

#192 - modal title size

---

framework/components/AApp/base/lists.scss

#188 - hard set padding for li elements

---

framework/components/ASelect/ASelect.js

#184 - focus menu on open ASelect

---

framework/components/ASelect/ASelect.js
framework/components/ASelect/ASelect.mdx

#183 - custom template options for ASelect

---

framework/components/APagination/APagination.scss

Incorrect spacing between buttons in APagniation component

---

framework/components/AStepper/AStepper.mdx
framework/components/AStepper/AStepper.scss

Resolves #190 
Remove `z-index: 1` from the AStep component. Removing it resolves the issue, so trying this solution for now.

#190 - remove z-index from icon in AStepper step

---

framework/components/ATag/ATag.js
framework/components/ATag/ATag.mdx
framework/components/ATag/ATag.scss

#176 add level to ATag for basic states

---

framework/components/AIcon/AIcon.scss

fill list-bullets icon

---

framework/components/AIcon/atomicMap.js
framework/components/AIcon/magnaIcons.js
svg/minus.svg

#214 add minus icon

---

framework/components/ABreadcrumb/ABreadcrumb.scss

Change fill to stroke on breadcrumb icons

---

framework/components/AHint/AHint.scss

Magnetic does not use italic font style

fix AHint typography

---

framework/components/ABreadcrumb/ABreadcrumb.js
framework/components/ABreadcrumb/ABreadcrumb.mdx
framework/components/ABreadcrumb/ABreadcrumb.scss

Breadcrumb now folow magnetic typography and hover state

fix ABreadcrumb style

---

framework/components/AAutocomplete/AAutocomplete.scss
framework/components/ACombobox/ACombobox.scss
framework/components/ATextInput/ATextInput.scss

Vertical text center alignment for AAutocomplete, ACombobox and ATextInput components

correction of vertical alignment at the inputs

---

framework/components/AAccordion/AAccordionHeaderTitle.js

fix missing caret-up icon in AAccordionHeader

---

framework/components/AButton/AButton.scss

fix small AButton component

---

framework/components/ACheckbox/ACheckbox.mdx
framework/components/ACheckbox/ACheckbox.scss

fixes horizontal spacing and vertical alignment of wrapped label

fix ACheckbox styles

---

framework/components/AApp/base/links.scss

#262 - quick style fix for icons inside links

---

framework/components/ASelect/ASelect.js
framework/components/ASelect/ASelect.spec.js

Feature update for ASelect, closes https://github.com/cisco-sbg-ui/magna-react/issues/260

ASelect - edge detection and top menu placement

---

framework/components/AApp/base/links.scss

#270 fix link button border radius

---

framework/styles/theme/default.scss
framework/styles/theme/dusk.scss

#251 - align tab bar hover color

---

framework/components/AFieldBase/AFieldBase.js
framework/components/ATextInput/ATextInput.js
framework/components/ATooltip/ATooltip.js
framework/components/ATooltip/index.js

This should fix prop type error I've accidentally introduced in #255.

fix prop type

---

framework/components/APageOverlay/APageOverlay.scss

fix: add overpowered z-index to APageOverlay

---

framework/components/ADrawer/ADrawer.js

condense reused ADrawer code

---

framework/components/AProgressbar/AProgressbar.js
framework/components/AProgressbar/AProgressbar.mdx
framework/components/AProgressbar/AProgressbar.scss

Add size variants to AProgressbar

---

framework/components/ASelect/ASelect.scss

#329 fix: Adjust margins and paddings for ASelect

---

framework/components/ACard/ACard.mdx
framework/components/ACard/ACard.scss
framework/components/ACard/ACardBasic.js
framework/components/ACard/ACardContainer.js
framework/components/ACard/ACardContent.js
framework/components/ACard/ACardFooter.js
framework/components/ACard/ACardHeader.js
framework/components/ACard/ACardItem.js
framework/components/ACard/ACardSubTitle.js
framework/components/ACard/ACardTitle.js
framework/components/ACard/index.js
framework/index.js
framework/styles/theme/default.scss
framework/styles/theme/dusk.scss

Add ACard component

---

framework/components/AIcon/AIcon.js
framework/components/AIcon/AIcon.scss

Resolves #333
This also fixes passing `style` to AIcon

fix: #333 fill for type_ icons

---

framework/components/AToaster/AToaster.mdx
framework/components/AToaster/useAToaster.js

feat: #336 use magnetic default timeouts for toasts

---

framework/components/ASpinner/ASpinner.js
framework/components/ASpinner/ASpinner.mdx
framework/components/ASpinner/ASpinner.scss
framework/components/ASpinner/index.js
framework/index.js
framework/styles/theme/default.scss
framework/styles/theme/dusk.scss

Magnetic spinner component

---

framework/components/AButton/AButton.scss

Fix hover color state for dot icons inside AButton

---

framework/components/ADataTable/ADataTable.scss
framework/components/ASimpleTable/ASimpleTable.scss

fix: #345 - selected row color specificity

---

framework/components/AApp/base/scrollbar.scss

@trent-boyd suggested using color-scheme for automatic scrollbar styling

Use color-scheme for scrollbars

---

framework/components/ASelect/ASelect.cy.js
framework/components/ASelect/ASelect.js
framework/components/ATextInput/ATextInput.cy.js
framework/components/ATextInput/ATextInput.js
framework/components/ATextInput/ATextInput.mdx
framework/components/ATextarea/ATextarea.cy.js
framework/components/ATextarea/ATextarea.js

#350 - allow override of internal validation rules on inputs

---

framework/components/AButton/AButton.scss

style: fix on tertiary

---

framework/components/ACombobox/ACombobox.js

Adds new props to `ACombobox` to align closer to options of `ASelect`

Add dropdownStyle and dropdownClassName to ACombobox

---

framework/components/ATabs/ATabs.scss

**Closes #354  - Tab adjustments to align more with magnetic details**
**Magnetic**
**Before**
**After**
**Before**
**After**

fix: tab adjustments to magnetic

---

framework/components/AButton/AButton.js
framework/components/AButton/AButton.scss

#367 - add loading prop to button; middle align vertically

---

framework/components/ATag/ATag.js
framework/components/ATag/ATag.mdx
framework/components/ATag/ATag.scss

This reverts commit b3da2d2dff6d83930fc3503952252c9821f9193c so that we can release a new version of Magna React under `1.0.0-beta.41` without a bug

hotfix: revert "style: handle long tags in ATag component"

---

framework/components/AFieldBase/AFieldBase.scss

381 - input tooltip icon hover color

---

framework/components/ADataTable/ADataTable.scss

#400 - remove padding/margin of checkbox when in data table

---

framework/components/ADataTable/ADataTable.scss

#374 - right align sort icon; show on hover

---

framework/components/ATag/ATag.mdx
framework/components/ATag/ATag.scss

#372 - wrapping tags, align padding/height/border radius with magnetic

---

framework/utils/helpers.js

Not used, was leftover from other code that was changed during review

Remove debounce function

---

framework/components/AMenuBase/AMenuBase.js

Should fix regression from https://github.com/cisco-sbg-ui/magna-react/pull/339.
Fixes https://github.com/advthreat/incident-manager/issues/948 (after magna-react bump).

fix tooltip positioning regression

---

framework/components/ACombobox/ACombobox.js
framework/components/ACombobox/ACombobox.scss
framework/components/AEmptyState/AEmptyState.js
framework/components/AEmptyState/AEmptyState.scss

Should use empty state component when filter doesn't match any items

Align ACombobox empty state with design

---

framework/components/ASwitch/ASwitch.js
framework/components/ASwitch/ASwitch.mdx
framework/components/ASwitch/ASwitch.scss

#433 align ASwitch with magnetic; add small variant

---

framework/components/AProgressbar/AProgressbar.js

#431 - add custom class and style props to AProgressbar elements

---

framework/components/ABadge/ABadge.mdx
framework/components/ABadge/ABadge.scss
framework/components/AButton/AButton.js
framework/components/AButton/AButton.scss
framework/components/AButtonGroup/AButtonGroup.js
framework/components/AInputBase/AInputBase.js
framework/components/ASelect/ASelect.js
framework/components/ASelect/ASelect.mdx
framework/components/ATextInput/ATextInput.mdx

Resolves #433
Addresses defaults for 
- AButton
- AButtonGroup
- ACombobox
- ASelect
- ATextInput

Default to medium size variant where applicable

---

framework/components/AMenu/AMenu.js
framework/components/AMultiSelect/AMultiSelect.cy.js
framework/components/AMultiSelect/AMultiSelect.js
framework/components/AMultiSelect/AMultiSelect.mdx
framework/components/AMultiSelect/AMultiSelect.scss
framework/components/AMultiSelect/AMultiSelect.spec.js
framework/components/AMultiSelect/AMultiSelectTag.js
framework/components/AMultiSelect/index.js
framework/components/ATag/ATag.scss
framework/index.js

Currently only supports tags. Resolves #404

feat: Add AMultiSelect component

---

framework/components/ATriggerTooltip/ATriggerTooltip.js
framework/styles/utilities/mixins.scss

Size should be 16px for medium 
https://www.figma.com/file/oVZWatImEIbl1c8sjdGxi0/branch/YNkCw8yeaOOOuvxWtyRz4X/%F0%9F%A7%B2--Magnetic-Design-Library?node-id=3200%3A21213&mode=dev

Icon button size

---

framework/components/ATriggerTooltip/ATriggerTooltip.js

Oversight, was missing from propTypes list

Add onlyIfTruncated prop to proptypes list

---

framework/components/ACheckbox/ACheckbox.js
framework/components/ACheckbox/ACheckbox.mdx
framework/components/ACheckbox/ACheckbox.scss
framework/styles/theme/default.scss
framework/styles/theme/dusk.scss
framework/styles/utilities/palette.scss

**Resolves #453 - Magnetic fixes and updates to ACheckbox**
- **"Visual" breaking change:** Medium is default as per magnetic docs: https://magnetic.cisco.com/0a43ab5cd/p/71e3ca-checkbox-
- Color updates to state as well as similar updates to button styles. (minor color shifts in the figma)

feat: magnetic adjustments and updates to checkbox

---

framework/components/ACheckbox/ACheckbox.scss

fix: resurrect hover color

---

framework/components/ADrawer/ADrawer.scss

fix: #467 - hide box shadow on hidden ADrawer

---

framework/components/ACheckbox/ACheckbox.js
framework/components/ACheckbox/ACheckbox.mdx

feat: Add withLabel prop to ACheckbox

---

framework/components/AMultiSelect/AMultiSelectTag.js

fix: multiselect tag size

---

framework/components/ACopyButton/ACopyButton.js
framework/components/ACopyButton/ACopyButton.mdx
framework/components/ACopyButton/ACopyButton.scss
framework/components/ACopyButton/index.js
framework/components/ATooltip/ATooltip.scss
framework/components/ATriggerTooltip/ATriggerTooltip.js
framework/index.js
framework/utils/helpers.js

feat: Add ACopyButton component

---

framework/components/ACopyButton/ACopyButton.js

Follow up to #464 -icon true to copy button

fix: follow up to #464 -icon true to copy button

---

framework/components/ADatePicker/ADateRangePicker.js

Closes #476  - Removes leftover ID

fix: remove leftover id

---

framework/components/ADatePicker/ADatePicker.mdx
framework/components/ADatePicker/ADatePicker.scss
framework/components/ADatePicker/ADateRangePicker.js
framework/components/ADatePicker/DateInputs.js

Closes #477 - Optional actionable label to date picker

feat: actionable label

---

framework/components/AModal/AModal.mdx
framework/components/AModal/AModal.scss

Modal examples use ACard; Remove close icons

---

framework/components/ADatePicker/ADatePicker.mdx
framework/components/ADatePicker/ADateRangePicker.js
framework/components/ADatePicker/DateInputs.js
framework/components/ADatePicker/helpers.js

**Fixes #484 - Handle various timezones and locale formats.** 
This is not a perfect system, however it seems to get the job done.  It handles most formats as long as there is a 4 digit year.  More detailed notes in PR.  
*Note: Page refresh is needed when swapping timezones in the browser.

feat: reasonably handle timezones and locale formats

---

framework/components/ACheckbox/ACheckbox.js
framework/components/ACheckbox/ACheckbox.mdx
framework/components/ACheckbox/ACheckbox.scss
framework/styles/theme/default.scss
framework/styles/theme/dusk.scss

Fix, closes #497
No, it should be backward compatible.
It would be useful to replace unchecked SVG with right size SVG.

fix: Support focus in ACheckbox (#497)

---

docs/MdxHeadings.js
docs/Playground.js
framework/components/ABreadcrumb/ABreadcrumb.scss
framework/components/ANetworkValue/ANetworkValue.js
framework/components/ANetworkValue/ANetworkValue.mdx
framework/components/ANetworkValue/ANetworkValue.scss
framework/components/ANetworkValue/index.js
framework/components/APageLayout/APageContainer.js
framework/components/APageLayout/APageContainer.scss
framework/components/APageLayout/APageDescription.js
framework/components/APageLayout/APageDescription.scss
framework/components/APageLayout/APageHeader.js
framework/components/APageLayout/APageHeader.scss
framework/components/APageLayout/APageLabel.js
framework/components/APageLayout/APageLabel.scss
framework/components/APageLayout/APageLayout.mdx
framework/components/APageLayout/APageTitle.js
framework/components/APageLayout/APageTitle.scss
framework/components/APageLayout/APageTitleContent.js
framework/components/APageLayout/APageTitleContent.scss
framework/components/APageLayout/APageTitleText.js
framework/components/APageLayout/content/APageTitleContentLeft.js
framework/components/APageLayout/content/APageTitleContentRight.js
framework/components/APageLayout/index.js
framework/components/ATabs/ATabs.scss
framework/index.js
pages/[[...route]]/index.js

Adds page layout components:
- APageContainer
- APageHeader
- APageTitle
- APageDescription
- APageLabel
- APageTitleContent
- APageTitleContentLeft
- APageTitleContentRight
- APageTitleText
Additional components:
- ANetworkValue

feat: Add page layout components

---

framework/components/ADatePicker/ADatePicker.js

**Resolves #509 - prevent calendar view from initializing on the minimum date.**

fix: remove minDate return

---

framework/components/APageLayout/APageLayout.mdx
framework/components/APageLayout/APageTitleContent.scss
framework/components/APageLayout/content/APageTitleContentRight.js

Add option for no left content for right aligned header content

---

framework/components/AAutocomplete/AAutocomplete.js
framework/components/AMultiSelect/AMultiSelect.js
framework/utils/helpers.js

**Resolves #491 - Add bold text to search**
Was a little tricky with mixing regex with jsx, but this seems to work for most purposes. Would need to be improved for the object items however.

feat: add bold text to matched letters

---

framework/components/AInlineInputBase/AInlineInputBase.js
framework/components/AInputBase/AInputBase.js

Resolves #523 - swap clear icon

fix: swap clear icon

---

framework/components/APageLayout/APageContainer.scss
framework/components/APageLayout/APageDescription.scss
framework/components/APageLayout/APageHeader.scss
framework/components/APageLayout/APageLayout.mdx
framework/components/APageLayout/APageTitle.scss

quick pass at swapping padding for margin

525 - swap to use padding, adjust a bit of spacing

---

framework/components/AApp/base/fonts.scss
framework/components/ANetworkValue/ANetworkValue.js
framework/components/ANetworkValue/ANetworkValue.mdx
framework/components/ANetworkValue/ANetworkValue.scss

Resolves #508 
Resolves #550
Updates `ANetworkValue` to use RobotoMono font, and adds a copy button and base support for truncation of value

Use RobotoMono font

---

framework/components/ACheckbox/ACheckbox.js
framework/components/ACombobox/ACombobox.js
framework/components/AMultiSelect/AMultiSelect.js
framework/components/ATextInput/ATextInput.js
framework/components/ATextarea/ATextarea.js

Add skipValidation prop to inputs

---

framework/components/AMenu/AMenu.scss
framework/components/AMenuBase/hooks.js

Resolves #562
Also resolves minor UX issue with empty state not centering in combobox menu

Rework state tracking in useMenuSpacing hook

---

framework/components/AButton/AButton.scss

remove anchor opacity in disabled state, allow button to handle it

---

framework/components/AInlineInputBase/AInlineInputBase.js
framework/components/AInlineInputBase/AInlineInputBase.mdx
framework/components/AInlineInputBase/AInlineInputBase.scss
framework/components/ATooltip/ATooltip.js
framework/components/ATooltip/ATooltip.mdx
framework/components/ATooltip/ATooltip.scss

Add prop passing for tooltips on inline edits

---

framework/components/AMultiSelect/AMultiSelect.js
framework/components/AMultiSelect/AMultiSelectCounter.js

Fix tooltip for multiselect counter

---

framework/components/ADataTable/ADataTable.js
framework/components/ADataTable/ADataTableCellTemplate.js
framework/components/ADataTable/ADataTableHeaderTemplate.js
framework/components/ADataTable/ADataTableRowTemplate.js

#578 - add onRowMouseEnter and onRowMouseLeave to ADataTable

---

framework/components/AMultiSelect/AMultiSelect.scss

fix: #579 - add max-height for multiselect menu

---

package-lock.json
package.json

NPM audit warned for breaking change  to `start-server-and-test`.  Everything seems to be working ok.

chore: update vulnerability

---

framework/components/ATheme/ATheme.js
framework/styles/magnetic-tokens/index.scss

Allows export and use of cds theming css vars

feat: add cds theme

---

framework/components/AButtonGroup/AButtonGroup.scss
framework/styles/theme/theme-map.scss

Specificity isn't always right when compiled into code
See casebook notes edit

Add important for hover in button group

---

framework/components/AKeyValue/AKeyValue.js
framework/components/AKeyValue/AKeyValue.mdx
framework/components/AKeyValue/AKeyValue.scss
framework/components/AKeyValue/AKeyValueTable.js
framework/components/AKeyValue/index.js
framework/index.js

https://magnetic.cisco.com/0a43ab5cd/p/31cdc6-key-value-pairs/b/417681

Add AKeyValue components

---

framework/components/ATextInput/ATextInput.mdx

Was causing a key warning from React

Add key to mdx example for append extra content

---

framework/components/ARadio/ARadio.js
framework/components/ARadio/ARadio.mdx
framework/components/ARadio/ARadio.scss
framework/components/ARadio/ARadioGroup.js
framework/components/ARadio/index.js
framework/index.js

#616 - Add ARadioGroup, small variant, and description prop

---

framework/components/ATheme/ATheme.js
framework/components/ATheme/ATheme.scss
framework/styles/utilities/variables.scss

Move var theming far away from scss imports.

fix: move new var theming out into ATheme

---

README.md
framework/components/AApp/base/helpers.scss
package.json

When rendering a flexbox container, it is often necessary to add individual `ml-*` or `mr-*` classes to each list item to introduce a space between flex items. However, when doing so, there is often a need to conditionally apply the class such that this class is **not** applied to the very first flex item when using a `margin-left`, or alternatively, the last flex item when using `margin-right`.
Such conditional logic can be avoided with the [`gap` CSS shorthand property](https://developer.mozilla.org/en-US/docs/Web/CSS/gap), which will only add the space *between* adjacent elements.
That being said, there has been some hesitation for using this within applications since we can't use the design system spacing sizes directly in our CSS with the gap property, e.g:
```scss
.container { …
```

feat: add "gap" css helper class

---

framework/components/AInlineInputBase/AInlineInputBase.scss

Align icons for AInlineInput

---

framework/components/AInlineInputBase/AInlineInputBase.js
framework/components/AInlineInputBase/AInlineInputBase.scss

Has an onKeyDown, but wasn't set to activate edit mode

Allow onKeyDown to activate edit mode on inline inputs

---

framework/components/ASelect/ASelect.js
framework/components/ASelect/ASelect.scss

ASelect - differentiate placeholder from selected text

---

framework/components/AFieldBase/AFieldBase.js
framework/components/AFieldBase/AFieldBase.scss

Should be red. Looks like the css got broken at some point;

Fix required label * color

---

framework/components/AApp/base/typography.scss
framework/components/ABadge/ABadge.scss
framework/components/ACarousel/_carousel.scss
framework/components/AContextualNotification/AContextualNotification.scss
framework/components/ADialog/ADialog.scss
framework/components/AEmptyState/AEmptyState.scss
framework/components/AHint/AHint.scss
framework/components/AIcon/AIcon.scss
framework/components/AInputBase/AInputBase.scss
framework/components/ALoader/ACiscoLoader.scss
framework/components/APanel/APanel.scss
framework/components/ARadio/ARadio.scss
framework/components/ASidebar/ASidebar.scss
framework/components/ASlider/ASlider.scss
framework/components/AStepper/AStepper.scss
framework/components/ATabs/ATabs.scss
framework/components/ATag/ATag.scss
framework/components/ATooltip/ATooltip.scss
framework/styles/utilities/variables.scss

**#617 - Phase 3 - Remove all references to palette** 
This update allows us to completed delete palette JS.  Left in for now to avoid breaking changes for others until we are ready to delete the files.

Phase 3 - Remove all references to palette

---

framework/components/ASwitch/ASwitch.cy.js
framework/components/ASwitch/ASwitch.js
framework/components/ASwitch/ASwitch.mdx
framework/components/ASwitch/ASwitch.scss

Adds focus state and keyboard toggling on "enter" key for `ASwitch`

Keyboard accessibility for ASwitch

---

framework/components/APagination/APagination.cy.js
framework/components/APagination/APagination.js
framework/components/APagination/APagination.scss

**Resolves #612 - Add disabled property**
- Adds disabled styles to actionable elements
- Also converts tests to .cy and adds disabled checks

Disabled pagination/#612

---

framework/components/AInputBase/AInputBase.scss
framework/components/AMultiSelect/AMultiSelect.js
framework/components/AMultiSelect/AMultiSelect.mdx
framework/components/AMultiSelect/AMultiSelect.scss

Adds
- `readOnlyInput` prop to leave menu active, but set the text input to `readOnly`
- `filterFunction` example in docs
Fixes
- `readOnly` state background color in inputs

MultiSelect readOnlyInput, fixes

---

framework/components/ACheckbox/ACheckbox.js
framework/components/AList/AListItem.js
framework/components/AMenu/AMenu.js

Check if focus is in an input element before trapping arrow keys

---

framework/components/ACheckbox/ACheckbox.js

Revert recent changes to checkbox

---

framework/components/ADrawer/ADrawer.js
framework/components/ADrawer/ADrawer.mdx
framework/components/ADrawer/ADrawer.scss
framework/components/ADrawer/ADrawerTitle.js
framework/components/AModal/AModal.cy.js
framework/components/AModal/AModal.js
framework/components/AModal/AModal.mdx
framework/hooks/useOutsideClick/useOutsideClick.js
framework/hooks/usePopupQuickExit/usePopupQuickExit.js
framework/hooks/useReturnFocusOnClose/useReturnFocusOnClose.js

Reapply the earlier commits for moving forward with v2.x

Reapply modal accessibility enhancements

---

docs/Sidebar.js

This adds some padding along the sidebar's x-axis.
Before:
After:

docs: add sidebar padding along x-axis

---

docs/Sidebar.js

Not quite sure what happened during the merge of #674, but it looks like the padding I added in #676 somehow got removed

docs: add left margin to sidebar

---

pages/[[...route]]/index.js

Fix code for inline alerts in docs

---

framework/components/AHint/AHint.scss
framework/components/APanel/APanel.scss
framework/components/ARadio/ARadio.scss
framework/components/ATabs/ATabs.scss
framework/components/ATag/ATag.scss

Remove remaining references to magnetic neutral

---

framework/components/ADataTable/ADataTable.scss

Seems to work? Tested locally.

fix: blind attempt safari fix

---

docs/PropsHelper.js
docs/Sidebar.js
framework/components/ADrawer/ADrawer.mdx

And cleanup other references to `onCloseButtonClick`

Props helper drawer cleanup

---

framework/components/AList/AList.scss
framework/components/AMenu/AMenu.cy.js
framework/components/AMenu/AMenu.js
framework/components/ASelect/ASelect.js
framework/components/ATabs/ATab.cy.js
framework/components/ATabs/ATabGroup.js

For cases when elements are combined with `AListItem`

Add focus trap to AMenu

---

framework/components/AAccordion/AAccordion.scss

https://github.com/cisco-sbg-ui/magna-react/issues/709
https://github.com/cisco-sbg-ui/magna-react/issues/709
No

fix: accordion style issue

---

framework/utils/helpers.js

Resolves #718
This needs to be backported to 1.x

#718 - add react import to helpers

---

framework/changelog.mdx
framework/components/AApp/AApp.mdx
framework/hooks/useABreakpoint/useABreakpoint.js
framework/hooks/useABreakpoint/useABreakpoint.mdx
framework/styles/utilities/variables.scss

Add additoinal breakpoints

---

package-lock.json
package.json

Clear warnings "breaking update", but everything seems to be working.

build: deps security update

---

framework/components/AApp/base/typography.scss

fix: code style

---

framework/components/AActivityTimeline/AActivityTimeline.mdx
framework/components/AActivityTimeline/AActivityTimeline.scss

chore: #733 color adjustments, #730 console warn

---

framework/components/AButton/AButton.scss
framework/components/AButtonGroup/AButtonGroup.scss

Align button focus outline state

---

framework/components/ADrawer/ADrawer.js
framework/components/ADrawer/ADrawer.mdx

Conditionally use prev children logic for drawer hook

---

framework/components/AButton/AButton.scss
framework/components/ADatePicker/ADatePicker.scss
framework/components/AInputBase/AInputBase.scss
framework/components/AMultiSelect/AMultiSelect.scss
framework/styles/utilities/mixins.scss

Resolves #755 
**Also fix for focus on negative btns**
**Before**
**After**

Focus style update + fix on negative btn

---

framework/components/AApp/base/typography.scss
pages/[[...route]]/index.scss

Move code background to be docs only

---

framework/components/AModal/AModal.mdx
framework/components/AModal/AModal.scss

787 - Adjust css to auto scroll modals to avoid running off the screen

---

framework/components/AModal/AModal.js
framework/components/AModal/AModal.mdx
framework/components/AModal/AModal.scss

Remove padding for a-card-container inside modals

---

framework/components/AFooter/AFooter.scss

Fix font color token for AFooter

---

framework/components/ACard/ACard.mdx
framework/components/ACard/ACard.scss
framework/components/ACard/ACardBasic.js

Add interactive prop for ACardBasic

---

framework/components/AIcon/AIcon.scss

Still didn't work in certain envs. @jflook10

fix: cisco logo again

---

framework/components/AMenuBase/AMenuBase.tsx
framework/utils/helpers.js

fix: fix tooltip pointer position

---

framework/components/ATriggerTooltip/ATriggerTooltip.tsx

Probably fixes something down the line

fix: pass isOpen boolean instead

---

framework/components/AActivityTimeline/types.ts
framework/components/AAutocomplete/types.ts
framework/components/ACheckbox/types.ts
framework/components/ACombobox/types.ts
framework/components/AContextualNotificationMenu/types.ts
framework/components/ADataTable/types.ts
framework/components/ADatePicker/types.ts
framework/components/AEmptyState/types.ts
framework/components/AFieldBase/types.ts
framework/components/AInView/types.ts
framework/components/AInputBase/types.ts
framework/components/AMenu/types.ts
framework/components/AMultiSelect/types.ts
framework/components/ANetworkValue/types.ts
framework/components/APopover/types.ts
framework/components/ARadio/types.ts
framework/components/ASelect/types.ts
framework/components/ASlider/types.ts
framework/components/AStepper/types.ts
framework/components/ASwitch/types.ts
framework/components/ATextInput/types.ts
framework/components/ATextarea/types.ts
framework/components/AToaster/types.ts
framework/components/ATree/types.ts
framework/hooks/useEscapeKeydown/useEscapeKeydown.d.ts
framework/hooks/usePopupQuickExit/usePopupQuickExit.ts

Branch for stray or missing typings that come up

fix: some stray typings

---

framework/components/ANetworkValue/types.ts

fix: anetwork-value optional types

---

framework/components/AMenuBase/AMenuBase.tsx

Comment out onHasScrolled from AMenuBase

---

framework/components/ATag/ATag.js
framework/components/ATag/ATag.mdx
framework/components/ATag/ATag.scss
framework/components/ATag/types.ts

feat: alert tag

---

framework/components/AProgressbar/AProgressbar.scss

fix: css label fix

---

framework/components/AButton/AButton.scss
framework/components/AIcon/AIcon.scss
framework/components/ATag/ATag.scss

Unset stroke

---

framework/styles/utilities/variables.scss

fix: breakpoints px

---

pages/[[...route]]/index.scss

**Resolves #793** 
Adds a little extra padding for better scrollability room in app so the mouse doesnt get trapped in code scroll

style: add padding

---

tsconfig.json

Extra nudge to avoid any lint warnings

build: add react reference to avoid warnings

---

framework/components/AAlert/AAlert.scss

Adjust sizing for AAlert to match design

---

framework/components/ATag/ATag.tsx

Cant recreate so not sure if this gets it

fix: add some types in

---

framework/components/APanel/APanel.scss
framework/components/APopover/APopover.scss
package-lock.json

**Resolves #870** 
* Includes audit vulnerability fixes
* Centers panel headers
* Removes the newly working box-shadow in panel headers (not sure why it was there to begin with).

style: fixs on panel header

---

framework/components/AFieldBase/AFieldBase.scss
framework/components/AInputBase/AInputBase.scss

Note* this is an issue only after deployment
**Before **
**After **
@radesai21

fix: fixes new random css ordering issue in amultiselect

---

framework/components/AButton/types.ts
framework/components/AIcon/AIcon.scss

fix: variable icon

---

framework/components/AFloatingMenu/AFloatingMenu.tsx
framework/components/AFloatingMenu/useFloatingDropdown.tsx

Sample code to test with
```
() => {
const [open, setOpen] = useState(false);
const [errors, setErrors] = useState([]);
const ref = useRef();
const formRef = useRef(null);
const [email, setEmail] = useState("");
const [favNum, setFavNum] = useState("");
const [comments, setComments] = useState("");
const [role, setRole] = useState(null);
return (
<>
<AButton onClick={() => setOpen(true)}>Start</AButton>
<AModal
key="modal"
aria-labelledby="modal-title"
isOpen={open}
onClose={() => setOpen(false)}>
<ACardBasic style={{width: "700px"}}>
<ACardHeader>
<ACardTitle id="modal-content">Embedded Form</ACardTitle>
</ACardHeader>
<ACardContent>
{errors.length > 0 && (
<AAlert className="my-2" level="danger" dismissable={false}>
There are {errors.length} validation errors on the form.
</AAlert>
)} …
```

Use fixed strategy for dropdown menus

---

framework/components/APaginator/APaginator.cy.js

Fix flakey APaginator test

---

next-env.d.ts
package-lock.json
package.json

Dependabot failing - passed locally so trying here

deps: next bump

---

framework/components/ADrawer/ADrawer.scss
framework/components/AFloatingMenu/AFloatingMenu.tsx
framework/components/AFloatingMenu/AFloatingMenuContainer.tsx
framework/components/AFloatingMenu/useFloatingDropdown.tsx

Test code
```
() => {
const leftDrawerContentRef = useRef();
const [isLeftOpen, setIsLeftOpen] = useState(false);
const rightDrawerContentRef = useRef();
const [isRightOpen, setIsRightOpen] = useState(false);
const bottomDrawerContentRef = useRef();
const [isBottomOpen, setIsBottomOpen] = useState(false);
const items = [
{id: 1, name: "Bread, Cereal, Rice, and Pasta"},
{id: 2, name: "Vegetables"},
{id: 3, name: "Fruit", selected: true},
{id: 4, name: "Milk, Yogudflsjgh sdljkfhg lsdjkfhgl kdsjfghldks jfghlkdjsfhg lkjsdfhg lkjdsfhg lkjsdfhg lkjdfghrt, and Cheese"},
{id: 5, name: "Meat, Poultry, Fish", disabled: true},
{id: 6, name: "Fats, Oils, and Sweets"}  
];
const [value1, setValue1] = useState([]);
const [value2, setValue2] = useState([]);
const [value3, setValue3] = useState([]); …
```

Fix extra wide menus in Drawers/Modals, handle closeOnOutsideClick

---

framework/components/AHint/AHintContainer.js

Allow React.Node for non-array hints

---

framework/components/AAutocomplete/AAutocomplete.js
framework/components/ACombobox/ACombobox.js
framework/components/AFloatingMenu/useFloatingDropdown.tsx
framework/components/AMultiSelect/AMultiSelect.js
framework/components/ASelect/ASelect.js

Temporarily disable this feature until we can explore further and give time for product test cases to be updated

Disable reference hidden check for dropdown menus

---

framework/components/AToast/AToast.scss
framework/components/AToast/AToast.tsx

style: style danger to warning

---

framework/components/AContextualNotificationMenu/AContextualNotificationMenu.js
framework/components/AFloatingBase/AFloatingBase.tsx
framework/components/AFloatingBase/types.ts
framework/components/AFloatingBase/useFloatingBase.tsx
framework/components/ATooltip/ATooltip.tsx
framework/components/ATriggerTooltip/ATriggerTooltip.tsx
framework/types/types.ts

Removes the `domRect` prop and combines it with `anchorRef`

Allow anchorRef to handle DOMRect

---

framework/components/AFloatingMenu/AFloatingMenu.tsx
framework/components/AFloatingMenu/AFloatingMenuContainer.tsx
framework/components/AFloatingMenu/types.ts

Needs to get set to the DOM element

Move the outside click attr to the list component

---

framework/components/AAlert/AAlert.scss
framework/components/AAlert/AAlert.tsx

**Resolves #910 - Fixes up some styles and old focus code:**

fix: alert close btn focus update

---

package-lock.json

Resolves npm audit vulnerabilities

deps: run npm audit fix

---

framework/components/AAlert/AAlert.tsx
framework/components/AButton/AButton.js
framework/components/ATag/ATag.js
framework/components/ATag/ATag.tsx
framework/components/AToast/AToast.tsx

Remove old `focus-box-shadow` class.

chore: remove unused css class

---

framework/components/ADivider/ADivider.d.ts
framework/components/ADivider/ADivider.js
framework/components/ADivider/ADivider.mdx
framework/components/ADivider/ADivider.scss
framework/components/ADivider/ADivider.tsx
framework/components/ADivider/types.ts

Vertical divider/#932

---

framework/components/ASkeleton/ASkeleton.mdx
framework/components/ASkeleton/ASkeleton.scss
framework/components/ASkeleton/ASkeletonBlock.js
framework/components/ASkeleton/ASkeletonText.js
framework/components/ASkeleton/types.ts

Allow ASkeleton components to be used without the wrapper

---

.github/PULL_REQUEST_TEMPLATE.md

docs: update PR language

---

framework/components/ADropdown/ADropdown.d.ts
framework/components/ADropdown/ADropdown.mdx
framework/components/ADropdown/ADropdown.tsx
framework/components/ADropdown/types.ts
framework/components/AFloatingMenu/useFloatingDropdown.tsx

-Extends option for dropdown only icon
-Convert to typescript
-Adjust types in floatingDropdown

feat: dropdown icon

---

.github/PULL_REQUEST_TEMPLATE.md

(attempt # 3)
Apparently the highlight green dash might be the trick? 🤞

fix: formatting

---

cypress/tests/ABadge.cy.tsx
cypress/tests/ASlider.cy.tsx
eslint.config.mjs
framework/components/AFieldBase/types.ts
framework/components/ASlider/ASlider.d.ts
framework/components/ASlider/ASlider.tsx
framework/components/ASlider/types.ts
framework/types/index.ts

**Follow up to #949: Add tests (pre conversion) converted to typescript.**
-	[x] This change has been integrated and tested against 2 out of 3 typescript applications 
(Not currently used in ts env, however tested against one.  Also tested and verified in another JS application where this component is currently used.
-	[x] This change passed unit tests in these applications -  N/A
-	[x] The changes are documented in component docs and changelog
-	[x] Test have been added or modified, if appropriate
-    [x] Convert component to tsx, if reasonable
I hope not

A slider b/#949 - Add tests and Typescript

---

eslint.config.mjs

I'm really bad about leaving console.log in...

Add no console log eslint rule

---

framework/components/AApp/base/reset.scss
framework/components/AList/AList.scss

-	[x] This change has been integrated and tested against 2 out of 3 typescript applications
-	[x] This change passed unit tests in these applications
-	[ ] The changes are documented in component docs and changelog
-	[ ] The ESLint plugin has been updated if a new component is added
-	[ ] Test have been added or modified, if appropriate
-	[ ] The component should be in typescript
-	[ ] The component should accept a class name as a prop, if appropriate
-	[ ] The component should accept a forward ref, if appropriate
-	[ ] Add tests in typescript, cypress/tests/*, if reasonable
If an application was manually applying a disabled attribute or class to a component, the …

style remove global disabled style

---

framework/components/ADropdown/ADropdown.cy.js
framework/components/ADropdown/ADropdown.mdx
framework/components/ADropdown/ADropdown.tsx
framework/components/ADropdown/types.ts
framework/components/AFloatingMenu/AFloatingMenu.tsx
framework/components/AFloatingMenu/AFloatingMenuContainer.tsx

Needed for integration with some UI elements that auto open dropdowns

Allow ADropdown to be controlled externally

---

framework/components/ASlider/ASlider.tsx
framework/components/ATriggerBase/ATriggerBase.tsx
framework/hooks/useOutsideClick/useOutsideClick.d.ts
tsconfig.json

… to fix compilation errors in securex-ui-monorepo so that we don't have set next.config.js to ignore compilation errors

Feat: turn on noUncheckedIndexedAccess 

---

framework/components/AAlert/AAlert.tsx
framework/components/ADrawer/ADrawer.cy.js
framework/components/ADropdown/ADropdown.mdx
framework/components/AForm/AForm.mdx
framework/components/AHint/AHint.js
framework/components/AMenu/AMenu.mdx
framework/components/AMenuBase/AMenuBase.mdx
framework/components/AModal/AModal.cy.js
framework/components/AModal/AModal.mdx
framework/components/AMount/AMount.mdx
framework/components/APageLayout/APageLayout.mdx
framework/components/APagination/APagination.mdx
framework/components/APanel/APanel.mdx
framework/components/APopover/APopover.mdx
framework/components/ASwitch/ASwitch.mdx
framework/components/ATabs/ATabs.mdx
framework/components/AToast/AToast.mdx
framework/components/AToast/AToast.tsx
framework/components/AToaster/AToaster.mdx
framework/components/AToaster/useAToaster.js
framework/components/ATooltip/ATooltip.mdx
framework/components/ATriggerPopover/ATriggerPopover.mdx
framework/components/ATriggerTooltip/ATriggerTooltip.mdx
pages/[[...route]]/index.js

Follow up to `Alert` components re: Dismissible vs dismissable docs and logic

chore: update docs and logic for dismissible

---

framework/components/AButton/AButton.js
framework/components/AButton/AButton.mdx
framework/components/AButton/AButton.scss

This is in the magnetic design, so I think it's fair to add it. Needed for some upcoming work

Add tertiary destructive button state

---

cypress/tests/AStepperCard.cy.tsx
framework/components/AStepperCard/AStepperCard.mdx
framework/components/AStepperCard/AStepperCard.scss
framework/components/AStepperCard/AStepperCard.tsx
framework/components/AStepperCard/AStepperCardContent.tsx
framework/components/AStepperCard/index.ts
framework/components/AStepperCard/types.ts
framework/index.ts

Create a stepper card. 
N/A
https://cisco-sbg.atlassian.net/browse/XDR-15679

XDR-5679 Shared Component: Tabbed Card Stepper
