- framework/components/ACheckbox/ACheckbox.js
- framework/components/ACheckbox/ACheckbox.mdx
- framework/components/ACheckbox/ACheckbox.scss
Only supports legacy size = 15px
Supports default = 15px, small = 16px, medium = 20px
no
> Add magnetic size options

- .github/PULL_REQUEST_TEMPLATE.md
- framework/components/ADrawer/ADrawerContent.js
Allows a user to pass a custom class to the `ADrawerContent` component.
* The `ADrawerContent` component does not accept a class name as a prop.
* The `ADrawerContent` component does not accept a forward ref.
* The `ADrawerContent` component accepts a class name as a prop.
* The `ADrawerContent` component accepts a forward ref.
No
Thought it would be a good idea to add these two type of common props to the pull request template in case somebody forgets about it while developing.
> fix: add prop for custom class to ADrawerContent

- framework/components/ADataTable/ADataTable.js
- framework/components/ADataTable/ADataTable.mdx
- framework/components/ADataTable/ADataTable.scss
Resolves #81 
This PR allows for passing style to the table header cell. Using this the header text will truncate if needed.
Given the nature of `<table>` and css, this does not make the table automatically truncate and size columns for responsive layouts. Other table implementations will need to be used for responsive design.
It is recommended to allow a table to horizontal scroll rather than truncate columns header text.
> Add basic truncation to table header cells

- framework/components/ADataTable/ADataTable.js
- framework/components/ADataTable/ADataTable.mdx
- framework/components/ADataTable/ADataTable.scss
This changes up the DOM structure to support auto truncation with text-overflow ellipsis. 
Note that this is potentially a breaking change with existing header css. Any existing overrides to this effect can hopefully be removed.
Use the `truncateHeaders` prop on `ADataTable` to set auto truncation. Basic example on demo is updated to use this prop
> Rework table header for auto truncation

- framework/components/AModal/AModal.js
- framework/components/AModal/AModal.mdx
- framework/components/AModal/AModal.scss
Resolves #111 
This PR adds a prop for each of the four sizes. Additionally, it adds `onClickOutside` so AModal can be a drop in replacement for ADialog
> #111 - add size variants for AModal

- framework/components/AInputBase/AInputBase.js
Resolves #117 
quick test code from Playground inside the docs
```
() => {
const [status, setStatus] = useState("default");
const [value, setValue] = useState("autoFocused clearable");
const [disabled, setDisabled] = useState(false);
useEffect(() => {
setInterval(() => {
setDisabled(true)
}, 2000)
setInterval(() => {
setDisabled(false)
}, 3000)
}, [setDisabled]);
return (
<>
<APanel>
<APanelHeader>
<div className="d-flex align-start">
<ATextInput
medium
style={{minWidth: 240}}
prependIcon="search"
placeholder="Search"
clearable
disabled={disabled}
/>
</div>
</APanelHeader>
</APanel>
<APanel>
<APanelHeader>
<div className="d-flex align-start">
<ATextInput
medium
style={{minWidth: 240}}
prependIcon="search"
placeholder="Search"
clearable
disabled={true}
/>
</div>
</APanelHeader>
</APanel> …
```
> #117 - don't hide icon in disabled state

- framework/components/ADataTable/ADataTable.js
- framework/components/ADataTable/ADataTable.mdx
- framework/components/ASkeleton/ASkeleton.js
- framework/components/ASkeleton/ASkeleton.mdx
To make it a bit easier to add a loading state to `ADataTable`, this PR allows the use of a row data object `{cellLoading: true}`. This can be combined with row data objects that have data, and should allow for a full table loading state and infinite scroll situations.
> Add a cellLoader to auto use ASkeleton

- framework/components/AButton/AButton.scss
- framework/components/AButtonGroup/AButtonGroup.scss
- framework/styles/utilities/mixins.scss
I think a mixin for the button size makes sense so that we can reuse it where needed, but this could also seem a bit excessive. I just worry about the `AButtonGroup` and `AButton` having different declarations for the same thing.
> refactor: add medium button styles to sass mixin

- framework/components/AButton/AButton.js
- framework/components/AButton/AButton.scss
- framework/components/AButtonGroup/AButtonGroup.js
- framework/components/AButtonGroup/AButtonGroup.mdx
- framework/components/AButtonGroup/AButtonGroup.scss
- framework/styles/utilities/mixins.scss
- Change `medium` css class to `a-button--medium`
- Add example of medium buttons inside AButtonGroup (verbose)
- Add `medium` prop to `AButtonGroup`
Resolves #155
> Scope AButton medium modifier css class

- framework/hooks/useOutsideClick.js
Closes #143 
`useOutsideClick` used the `click` event listener, which is fired *after* the `mousedown` listener, meaning that there were possibilities for race conditions as it related to components unmounting within the `useOutsideClick`'s container element.
This PR updates `useOutsideClick` to listen to `mousedown` events, meaning that we will be alerted about outside clicks to the container element *before* the user finishes their click. 
[MDN's note about the `mousedown` event](https://developer.mozilla.org/en-US/docs/Web/API/Element/mousedown_event)
> Note: This differs from the [click](https://developer.mozilla.org/en-US/docs/Web/API/Element/click_event) event in that click is fired after a full click action occurs; that is, the mouse button is pressed and released while the pointer …
> fix: listen for mousedown events in useOutsideClick

- framework/components/AMenu/AMenu.scss
Resolves #152 
Note that this breaks the example with custom styling for border radius on the menu, but does fix the default rounded border case.
See "More Menu" button on the Storybook
> #152 - fix border radius for first and last menu item

- framework/components/AMount/AMount.js
Adds check on the combined ref for the root class `.a-app` in an effort to check if the `AMount` is the app root or a nested mount.
Resolves #145
> #145 - check if parent a-app to add AToastPlate

- framework/components/AMenuBase/AMenuBase.js
Closes #171 by syncing the `click` event listeners that are added/removed within `AMenu`.
> fix: sync addition and removal of event listener for AMenu click outside

- framework/components/ADataTable/ADataTable.js
- framework/components/ADataTable/ADataTable.mdx
Resolves #177
- Adds `toggleSort` prop to `ADataTable` to swap behavior to simple sorting that skips the "unsorted" state
> #177 - add toggleSort prop to ADataTable

- framework/components/ASimpleTable/ASimpleTable.js
- framework/components/ASimpleTable/ASimpleTable.scss
Resolves #178
- Adjust compact row height to end up at ~38px 
- Default to `compact` table variant
> #178 - default to compact; adjust compact row height

- framework/components/ATabs/ATab.js
- framework/components/ATabs/ATabGroup.js
- framework/components/ATabs/ATabs.mdx
- framework/components/ATabs/ATabs.scss
- framework/styles/theme/default.scss
- framework/styles/utilities/mixins.scss
Resolves #179 by adding a `vertical` prop to `ATabGroup` that will render the tabs vertically. See the [vertical tabs](https://magna-react-git-feat-vertical-tabs.securex-preview.app/components/tab#vertical-tabs) and [oversized vertical tabs](https://magna-react-git-feat-vertical-tabs.securex-preview.app/components/tab#oversized-vertical) demos.
> feat: add vertical tabs prop to ATabGroup

- framework/components/AAccordion/AAccordion.mdx
- framework/components/AModal/AModal.js
Resolves #191 by stopping events from bubbling outside of `AModal`.
The key thing to note is that even though `AModal` is rendered as a React Portal, React will *still* treat the component as a child of the **React tree** it was rendered in, meaning that [events happening inside of the React Portal will bubble up to their parent components](https://reactjs.org/docs/portals.html#event-bubbling-through-portals).
<details>
<summary>
The solution is to invoke the `stopPropagation()` method from the root component rendered in `AModal`. If you're still not entirely comfortable with this fix, or what what React means by "Event Bubbling Through Portals", then you can expand this snippet to get a lot more information.
</summary>
As a quick refresher on bubbling behavior, let's look at the …
> fix: stop event bubbling in AModal

- framework/components/AIcon/AIcon.js
- framework/components/AIcon/atomicMap.mjs
- scripts/copyPhosphorIcons.mjs
Some apps bundling Magna React are having issues with the `atomicMap.js` file using Common JS module syntax. This PR converts the file to ESM module syntax, and updates imports across the repo accordingly.
> fix: export icon map using esm module syntax

- framework/components/APagination/APagination.scss
Pull request solves the undesirable shift of the selected button by 2px to the left which occurred due to inheritance from the AButtonGroup component
> correction of displaced selected button in APagination component

- framework/components/APagination/APagination.js
Paging arrows now follow Magnetic rules
> fix paging arrows in APagination component

- framework/components/ADrawer/ADrawer.scss
`transition: all` in `ADrawer` causes unwanted transitions when setting other css attributes on `ADrawer` from outside. 
Specifically this `top` attribute to offset the drawer below the shell app header causes the drawer to slide in from the top: https://github.com/advthreat/intelligence/blob/master/src/components/Drawer/Drawer.js#L35 
https://user-images.githubusercontent.com/51229231/222739718-66fad22a-f0e9-4739-9acc-28c5071a5053.mov
This has not been apparent until recently. Every drawer was mounted on the page as hidden when the page loaded, so the transition from `top` ran in a hidden state. Now we mount/unmount drawers on demand when we want to show/hide them. This makes the `top` transition run after mounting/showing the drawer.
Side note: Looks like browsers automatically delay …
> Limit drawer transition attributes to avoid unwanted animations

- framework/components/AAccordion/AAccordion.mdx
- framework/components/AModal/AModal.js
Similar to #202 , this PR also resolves #191 by stopping event propagation for `keydown` events if they are not triggered from the escape key (in order to preserve quick escape functionality). 
These become relevant in situations such as when a Modal is rendered within a button.
```javascript
<AButton>
<AModal>
{/* Clicks/key presses in here propagate to `AButton` */}
</AModal>
</AButton>
```
To see this in action, navigate to [Magna React Modal documentation](https://magna-react.vercel.app/components/modal#usage), and paste the following code snippet into a playground editor. Then, once opening the modal, click your enter key or spacebar to see the accordion open/close while the modal is opened.
* Note: when opening the modal, focus will automatically be set to the "X" button (expected). …
> fix: stop keydown event bubbling in AModal

- framework/components/AFieldBase/AFieldBase.js
- framework/components/ATextInput/ATextInput.js
Fixes #254 by allowing me to set `placement` prop on the `infoTooltip`.
> Add support for setting infoTooltip props

- framework/styles/theme/default.scss
- framework/styles/theme/dusk.scss
- framework/styles/utilities/palette.scss
Resolves #243 
Note: dark theme colors are a best guess since Magnetic still doesn't have an official dark theme, and there are at least three different base colors for info across multiple current source of truth figmas.
> #243 - closer sync to current design for status colors

- framework/components/AMenuBase/AMenuBase.js
- framework/hooks/useOutsideClick.js
This fixes the issue related to `ASelect` components closing a hypothetical `AModal` they are rendered in. It's important to note that issue was not exclusive to `ASelect`. It was happening for all components that render `AMenuBase`.
This PR:
* Aligns outside click logic in `AMenuBase` to use the same event listener as `useOutsideClick` that was changed in #162
* Ignores outside click events from elements specifying a `[data-ignore-outside-click]` data attribute.
<details>
<summary>To test this out, paste the following snippet into any playground editor from <a href="https://magna-react-git-fix-modal-with-select.securex-preview.app/components/modal">this preview branch</a></summary>
```js
() => {
const items = [
{ id: 1, name: "Bread, Cereal, Rice, and Pasta" },
{ id: 2, name: …
```
> fix: prevent AMenu components from closing AModal

- framework/components/AModal/AModal.js
Closes #263 by returning a cleanup function from the `AModal` `useEffect` to prevent body scroll when the component unmounts.
This was causing problems when `AModal` was conditionally rendered, like below:
```jsx
() => {
const [open, setOpen] = useState(false);
const ref = useRef();
usePopupQuickExit({
popupRef: ref,
isEnabled: open,
onExit: () => setOpen(false)
});
return (
<div>
<AButton
onClick={() => setOpen(true)}>
Open Modal
</AButton>
{open && (
<AModal
aria-labelledby='modal-title'
isOpen={open}>
<APanel ref={ref} style={{ minWidth: '400px' }} type="dialog">
<APanelHeader>
<APanelTitle id='modal-title'>Modal Demo</APanelTitle>
<AButton aria-label="Close modal 1" onClick={() => setOpen(false)} tertiaryAlt icon>
<AIcon>close</AIcon>
</AButton>
</APanelHeader>
<APanelBody>
Modal …
```
> fix: cleanup body scroll when AModal unmounts

- framework/components/AFieldBase/AFieldBase.js
- framework/components/ATooltip/ATooltip.js
- framework/components/ATooltip/ATooltip.mdx
- framework/components/ATriggerTooltip/ATriggerTooltip.js
- framework/components/ATriggerTooltip/ATriggerTooltip.mdx
- framework/components/ATriggerTooltip/index.js
- framework/hooks/useToggle/useToggle.js
- framework/hooks/useToggle/useToggle.mdx
- framework/index.js
Adds `useToggle` as a hook for controlling components with an "open" prop. Provides
- isOpen state prop
- function to open by event
- function to close by event
- function to toggle by event
`const {isOpen, open, close} = useToggle(400, 0);`
> Add useToggle hook for delay open of tooltip

- framework/components/ACombobox/ACombobox.js
- framework/components/AMenuBase/hooks.js
- framework/components/ASelect/ASelect.js
Adds bottom edge detection to ACombobox. Logic has been abstracted into the `useMenuSpacing` hook. 
This should potentially be enhanced to add scroll detection to recalculate the menu placement.
> Abstract menu placement into a hook; use hook in ASelect and ACombobox

- framework/components/AModal/AModal.js
- framework/hooks/useFocusTrap/useFocusTrap.js
- framework/hooks/useFocusTrap/useFocustrap.mdx
- framework/utils/helpers.js
Closes #283 by updating the `useFocusTrap` [`TreeWalker` instance](https://developer.mozilla.org/en-US/docs/Web/API/TreeWalker) to accept the root (parent) node of the trap. This allows the focus trap to determine its first and last child, which allows for "roving" behavior.
This PR also fixes an issue related to the focus trap not working in a Modal due to the strict `e.stopPropagation()` behavior on `keydown` events inside that component which was merged in #244.
For a demonstration, navigate to [this preview branch's `useFocusTrap` docs](https://magna-react-git-feat-roving-focus-trap.securex-preview.app/hooks/use-focus-trap#usage) and constantly press either <kbd>Tab</kbd> or <kbd>Shift + Tab</kbd>. Focus will circulate through the trap.
> feat: implement roving focus in useFocusTrap

- framework/components/AModal/AModal.js
Resolves #287 by overcoming my Friday afternoon programming miseries.
In all seriousness, the reason this bug was happening was because I forgot to return the variable that determines if we should stop propagation on keydown events, hence why an `Enter` or `Space` click was closing an accordion when the Modal was rendered inside of it.
<details>
<summary>Reproduction code block</summary>
```javascript
() => {
const [open, setOpen] = useState(false);
const ref = useRef();
usePopupQuickExit({
popupRef: ref,
isEnabled: open,
onExit: () => setOpen(false),
});
return (
<div>
<AAccordion>
<AAccordionPanel>
<AAccordionHeader>
<AAccordionHeaderTitle>
Accordion Title{" "}
<AButton onClick={(e) => {
e.stopPropagation();
setOpen(true);
}}>Open Modal</AButton>{" "}
<Modal isOpen={open} /> …
```
> fix: return boolean from modal propagation helper

- framework/components/ASkeleton/ASkeleton.js
- framework/components/ASkeleton/ASkeleton.mdx
Since ASkeleton is used as a loader state more often than not, set `animate` to true for the default.
> Default animate skeleton

- framework/components/ATriggerTooltip/ATriggerTooltip.js
- framework/components/ATriggerTooltip/ATriggerTooltip.mdx
Relaxes `ATriggerTooltip` content prop type a bit to allow formatting without warnings.
> Support rich ATriggerTooltip content

- framework/components/ADataTable/ADataTable.mdx
- framework/components/ADrawer/ADrawer.js
- framework/components/ADrawer/ADrawer.mdx
- framework/components/ADrawer/ADrawer.scss
- framework/components/ADrawer/ADrawerContent.scss
Closes #292 - Add close button option to drawer.  
- Adds options for close icon or a title
- Skipped className as usage of this is unlikely at this time.
- Adjustment on `ADrawerContent` padding.  Most repos are overwriting the `24px` with `padding: 16px 24px` so if you can't beat em'--
**Button with icon**
**Button with title**
**Functionality**
> Close drawer/#292

- framework/components/ADataTable/ADataTable.mdx
- framework/components/ADrawer/ADrawer.js
- framework/components/ADrawer/ADrawer.mdx
- framework/components/ADrawer/ADrawer.scss
Had to move to absolute due to need for flex column display coming from Apps.  Unfortunately, this means content on left will overflow again (which is what we were trying to solve for) so this means overflow will need to be managed in the element next to it here and there. Ideally it would be nice to have option to control header content and its children with ADrawerHeader, but the refactor necessary for that to happen in the apps would be quite a rewrite on their part.
> refactor: btn to absolute

- framework/components/ASkeleton/ASkeleton.scss
- framework/styles/utilities/index.scss
- framework/styles/utilities/keyframes.scss
They keyframes file was causing the keyframe to get imported into every component's scss.
> remove keyframes file; move skeleton shine to component scss

- framework/components/ALoader/ALoader.mdx
- framework/components/ALoader/ASpinLoader.js
- framework/components/ALoader/ASpinLoader.scss
- framework/components/ALoader/index.js
- framework/index.js
- framework/styles/theme/default.scss
- framework/styles/theme/dusk.scss
Part of #305 
Adds new `ASpinLoader` component. The component handles the basic spinner in small, medium, and large variants. It allows allows for children and placing the children around the spinner to match variants in the design.
> Add ASpinLoader component

- framework/components/AHint/AHint.js
Leaving the prop on `AAlert` for use elsewhere, but not setting it for validation states in `AFieldBase`
Resolves #306
> #306 - don't use fitContentWidth for validation state alert

- framework/components/AProgressbar/AProgressbar.js
- framework/components/AProgressbar/AProgressbar.mdx
- framework/components/AProgressbar/AProgressbar.scss
Allows the animation duration to be specified as a prop. If not passed, it will use the value set in the scss file.
> feat: add prop to set animation duration for AProgressbar

- framework/components/ATooltip/index.js
- framework/index.js
The logic inside the [`generate-babel-preset.js` script](https://github.com/cisco-sbg-ui/magna-react/blob/canary/build/generate-babel-preset.js) to prepare Magna React components for `babel-plugin-auto-import` does not handle the way `ATooltip` recently began exporting its components in #278.
Previously, `generate-babel-preset.js` would output the following for `babel-plugin-auto-import` to consume:
```json
{
"default": "ATooltip",
"path": "@cisco-sbg-ui/magna-react/lib/components/ATooltip"
} 
```
Currently, it looks like this:
```json
{
"default": "ATooltipExports",
"members": ["default", "ATooltipPropTypes"],
"path": "@cisco-sbg-ui/magna-react/lib/components/ATooltip"
} 
```
`ATooltip` was never mapped in the `ATooltipExports` `members`, hence why some consuming applications were …
> fix: update tooltip export style to fix automatic import

- framework/components/ATriggerTooltip/ATriggerTooltip.js
- framework/components/ATriggerTooltip/ATriggerTooltip.mdx
Adds `wrapChildren` and `wrapperClass` to `ATriggerTooltip`
This is intended to be used to allow tooltips on `disabled` elements, such as `<AButton disabled>Disabled Button</AButton>`. 
Resolves #307
> #307 add wrapChildren prop to ATriggerTooltip

- framework/components/ATriggerTooltip/ATriggerTooltip.js
Properly imports `ATooltip` as a result of #316
> fix(ATriggerTooltip): import ATooltip as named import

- framework/components/AList/AList.mdx
- framework/components/AList/AList.scss
- framework/components/AList/AListItem.js
- framework/components/AList/AListItemDivider.js
- framework/components/AList/AListItemDivider.scss
- framework/components/AList/AListItemGroup.js
- framework/components/AList/AListItemGroup.scss
- framework/components/AList/index.js
- framework/components/AMenu/AMenu.mdx
- framework/index.js
- framework/styles/theme/default.scss
- framework/styles/theme/dusk.scss
This PR introduces new feature to group list items (`AListItem`) under one unifying title as requested in Magnetic design. 
Closes #318 
Current behaviour doesn't support such grouping. 
New behaviour supports grouping using `AListItemGroup` component. Docs was updated and contains this new component usage for "Lists" as well as "Menus".
No, this change should be backward compatible.
> Added AListItemGroup to be able to group list items into unified set #318

- framework/components/ADrawer/ADrawer.cy.js
- framework/components/AModal/AModal.cy.js
- framework/components/APageOverlay/APageOverlay.scss
- framework/components/AToast/AToast.js
- framework/components/AToaster/useAToaster.js
Resolves #297 by adding the `data-ignore-outside-click` property so that Magna React's `useOutsideClick` hook knows to overlook any clicks coming from inside a toast. This is useful in scenarios when a drawer or modal is opened.
> fix(AToast, APageOverlay): add data attribute to ignore outside clicks and decrease z-index value

- framework/components/AMenu/AMenu.js
- framework/components/AMenuBase/AMenuBase.js
- framework/components/ASelect/ASelect.js
- framework/components/ASelect/ASelect.mdx
- framework/components/ASelect/ASelect.scss
Adds two props to ASelect
textWrapMenuItems | If item display is a string (no template), set white-space:normal on each item and limit width of the menu.Boolean | null
-- | -- | --
truncateMenuItems | If item display is a string (no template), truncate the display string with ellipsis and limit width of the menu.Boolean | null
Resolves #337
> feat: #337 add options to ASelect to handle long menu items

- docs/mock_modules.js
- framework/components/AMenuBase/AMenuBase.cy.js
- framework/components/AMenuBase/AMenuBase.js
- framework/components/AModal/AModal.scss
- framework/components/AMount/AMount.js
- framework/components/AMount/AMount.mdx
- framework/components/AMount/AMount.scss
- pages/[[...route]]/index.js
This PR allows a child of `AMount` to determine the edge detection settings by passing `withNewWrappingContext={true}` to the component.
Example:
```jsx
<AMount>
<div> {/* <-- this div is the new edge determinator */}
Is this PR a feature or fix? Probably a feafix or fixeat.
</div>
</AMount>
```
This is better demonstrated on the [example docs](https://magna-react-pfy3lvsn7.securex-preview.app/components/mount).
> feat(AMount): allow children to determine edge detection menu calculations

- framework/components/AToaster/customTimeout.js
- framework/components/AToaster/useAToaster.js
- framework/utils/PausableTimeout.js
Based on the pabst-components Notifier functionality, this will pause the dismiss timeout of an `AToast` generated by `useAToaster` when the user hovers over the toast message. 
Originally this was a request from users and UX to give more time to read some notifications.
Functionality:
1. Toast message is generated with a default 6 second timeout (#336)
2. User hovers over toast after 2 seconds
3. Timeout is paused indefinitely until user hovers away
4. Timeout resumes with 4 seconds left
5. Toast dismisses after 4 seconds
> feat: Pause toast timeout on hover

- framework/components/AButton/AButton.scss
Closes #359
Quick fix on button loader colors:
Note* Thinking since it looks like the button loaders are standardized in magnetic, magna could probably handle it all through a loading prop.
> fix: button spinner color

- framework/components/AContextualNotificationMenu/AContextualNotificationMenu.js
- framework/components/AMenu/AMenu.js
- framework/components/AMenuBase/AMenuBase.cy.js
- framework/components/AMenuBase/AMenuBase.js
- framework/components/APopover/APopover.js
- framework/components/ATooltip/ATooltip.js
Resolves #357 
Usage:
```jsx
const x = 100;
const y = 250;
<ATooltip anchorRef={new DOMRect(x, y)} />
```
I updated prop-types for this, too. It might be annoying having the `DOMRect` properties copied for each component that requires an `anchorRef` prop-type declaration, but I can't do `PropTypes.instanceOf(DOMRect)` because the `window` is only available at runtime.
I have also gone ahead and added conditional checks for any components expecting `anchorRef` to be a React `ref`, e.g., when trying to call the `focus` method on a DOM node. In this case I can explicitly do an `anchorRef instanceof DOMRect` check.
> feat: allow DOMRect objects to be passed to anchorRef props

- framework/components/AInlineInputBase/AInlineInputBase.js
- framework/components/AInlineTextInput/AInlineTextInput.js
- framework/components/AInlineTextarea/AInlineTextarea.js
Adds a prop `showTooltip` to add a tooltip of the display value to the value when the inline edit is not active
> feat: add tooltip prop for AInlineInputBase

- framework/components/ADrawer/ADrawer.cy.js
- framework/components/ADrawer/ADrawer.js
- framework/components/ADrawer/ADrawer.mdx
- framework/components/ADrawer/ADrawer.scss
- framework/components/AModal/AModal.cy.js
- framework/components/AModal/AModal.js
- framework/components/AModal/AModal.mdx
- framework/components/AModal/AModal.scss
- framework/utils/hooks.js
~~I would feel better merging this after #321.~~ Done
[Demo](https://magna-react-git-refactor-drawer-mounting-transitions.securex-preview.app/components/modal#usage)
There are two new props to make `AModal` more flexible for integrating applications.
*  `withCenteredContent`: Determines if the content rendered in the modal should automatically be centered vertically and horizontally.
* `withTransitions`: Determines if the modal will open and close with the fade-in and grow transitions
Props are changing to keep naming consistency with the other `AModal` props, making it easier to remember what can be passed.
* `trapFocus` renamed to `withFocusTrap`
* `lockScroll` renamed to `withScrollLock`
* CSS transitions for both the open and close states
<details>
<summary>:warning: Children of …
> feat: conditionally render modal and drawer children

- framework/components/AModal/AModal.js
I forgot to add documentation for the `delayUnmount`. This adds that in the prop types.
Just to note; this prop is very unlikely to be used, but I figured it's definitely better to document it than not.
> docs(AModal): document delayUnmount prop

- framework/components/AButton/AButton.js
- framework/components/AButton/AButton.mdx
This adds documentation for the loading button, as well as handles the case where a loading button maybe be rendered within an "icon only" button. In that case, the icon only button's icon gets entirely replaced by the loading spinner. This isn't in the Magnetic specs, but it sorta just "feels right". Let me know if otherwise; I can easily remove.
> feat: replace icon only button icon with spinner if loading

- framework/components/ATabs/ATabGroup.js
- framework/utils/helpers.js
When the parent container of ATabGroup changes size, the scrolling feature doesn't recalculate if the buttons should still be showing, or need to appear. This adds a ResizeObserver to check the parent container for size changes and trigger a show/hide of the buttons if needed.
> Add a resize observer to the tabs parent container to check if scroll buttons should show/hide

- framework/components/AButton/AButton.js
- framework/components/AButton/AButton.scss
**Resolves #406 Prevent button events when disabled.**
**Problem**
`pointer-events: auto` allows click actions on links
`pointer-events: none` will prevent `cursor: not-allowed` from displaying
**Solution** 
Put a wrapper on the button to display `cursor: not-allowed` while preventing click action in child.
**Before**
**After**
> fix: disable pointer events

- framework/components/AModal/AModal.cy.js
- framework/components/AModal/AModal.js
- framework/hooks/useFocusTrap/useFocusTrap.cy.js
- framework/hooks/useFocusTrap/useFocusTrap.js
- framework/hooks/useFocusTrap/useFocustrap.mdx
fix #395, fix #396
For #395, this change allows to opt-out from the implicit auto focus, which is part of the focus trap.
For #396, this change stops focusing the first focusable element and focuses the whole dialog instead.
> feat: allow to specify which element to focus when a modal is opened, or opt-out from the autofocus while keeping the trap available

- framework/components/AButton/AButton.cy.js
- framework/components/AButton/AButton.js
- framework/components/AButton/AButton.scss
Closes #409 - Hide icon when loading. 
*Note I targeted magna icons only, but it works with generic svg as well if we think people wont be passing in magna icons.
> fix: hide icon when loading

- framework/hooks/useFocusTrap/useFocusTrap.js
> fix: fallback to focusing root element when the provided reference is empty

- framework/components/ADataTable/ADataTable.js
- framework/components/ADataTable/ADataTable.scss
Closes #415 Adds a basic sticky header option.
@rwharrisjr  For the fixed pagination request, I feel like that is up to the table height and making sure there is scroll enabled on the table rather than the page.  What are your thoughts on that?
> feat: sticky header on scroll

- framework/components/ATextInput/ATextInput.cy.js
- framework/components/ATextInput/ATextInput.js
The clear icon should be displayed if and only if the value is a non-empty string, regardless of how that happened. Instead of manual syncing a separate state to determine whether the value fulfills this condition, this patch uses the value itself to determine if the clear icon should be displayed or not. It also takes the `clearable` property into account again, so the clear icon can only be shown when the text input is set to be `clearable`.
fix #422, fix #423, fix #425
> fix: display clear icon in text input based on the actual input value

- framework/components/AList/AList.scss
- framework/components/AList/AListItem.js
- framework/components/AMenu/AMenu.cy.js
- framework/components/AMenu/AMenu.js
- framework/components/AMenu/AMenu.mdx
- framework/components/AMenu/AMenu.scss
Resolved #403 - This provides an option for `AMenus` to display a list of items which may include submenus. Usage of the current components was ideal to allow flexibility,  familiarity, and a lot less duplicate code.  
*I also expanded the width of the menus to be more like magnetic- they were unusually slim.
**Usage**
To convert a list item into a submenu list item, `<AListItem />` and the nested `<AMenu />` will need these props:
**AListItem**
`ref` - Your list item ref
`submenu` - Boolean which will allow submenu styling and behavior
**AMenu**
`anchorRef`  - The target ref
`submenu` - Boolean which will allow submenu behavior
Once this is provided you may nest as many submenus as your heart desires.  Magentic prefers a limit of 2 cascading menus as described here: …
> feat: submenus

- framework/components/ADataTable/ADataTable.scss
Closes #432: Removing this CSS as it caused style issues on current tables depending on the order of the css.  
In the meantime, sticky header will have to go without a bottom border on scroll until we can figure out a better solution to keep a border on to help separate that content.
> fix: ressurect table lines

- framework/components/ATriggerTooltip/ATriggerTooltip.js
- framework/components/ATriggerTooltip/ATriggerTooltip.mdx
- framework/hooks/useToggle/useToggle.js
- framework/hooks/useToggle/useToggle.mdx
Adds `onlyIfTrunctated` prop to ATriggerTooltip to only show the tooltip if the content is truncated in some way.
@vdineva I think this will solve your use case, but it might not be a robust enough check. We can tweak it going forward if needed.
> #371 - add onlyIfTrunctated to ATriggerTooltip

- framework/components/AInputBase/AInputBase.scss
#424 Trying to find the simplest solution here.  So there is a flex on the sibling `a-field-base` which I wanted to avoid because I see that being used elsewhere like checkboxes. So tried just targeting the input base class instead - Looks like it works well in all the various input scenarios that I tested with.
> fix: stabilize width on input fields

- framework/changelog.mdx
- framework/components/ADatePicker/ADatePicker.scss
- framework/components/ADialog/ADialog.scss
- framework/components/ADrawer/ADrawer.scss
- framework/components/AMenuBase/AMenuBase.scss
- framework/components/APageOverlay/APageOverlay.scss
- framework/components/APanel/APanel.mdx
- framework/components/ASidebar/ASidebar.scss
- framework/components/ASlider/ASlider.scss
- framework/components/ATimeline/ATimeline.scss
- framework/components/AToaster/AToaster.scss
- framework/components/ATooltip/ATooltip.scss
- package-lock.json
- package.json
- pages/[[...route]]/index.js
- with recent changes on full screen in incident-manager we need to adjust library z-indexes to have space for full screen
Supports #766
`ADialog`, `AMenuBase` and `APageOveraly` `z-index` was changed. Now there is sufficient space in components `z-index`es to show full screen properly.
Yes, this pull request (PR) has the potential to cause issues. The "z-index" has been modified for some components, and if any custom components have manually set "z-index" values, it could disrupt the intended layering between them.
> fix: update z-index of various components (#766)

- framework/changelog.mdx
- framework/components/AMenuBase/AMenuBase.scss
- framework/components/AModal/AModal.cy.js
Form elements with menus (`ASelect`) inside `AModal` are opening the menu behind the modal
https://magna-react.vercel.app/components/modal
This bumps the `AMenuBase` z-index to 750, which is 50 higher than the new 700 for `APageOverlay`
@guptar8jan fyi
> Bump AMenuBase z-index to account for modals

- framework/components/ADataTable/ADataTable.scss
- framework/components/ASimpleTable/ASimpleTable.js
- framework/components/ASimpleTable/ASimpleTable.scss
Follow up to https://github.com/cisco-sbg-ui/magna-react/pull/437 and [#415 ](https://github.com/cisco-sbg-ui/magna-react/pull/421) - a non-invasive way to add "border" on scroll.  Used box-shadow - it's not as thick as the original border on scroll, but it helps.  Also added stickyHeader to `simple-table`.
> feat: add border on scroll

- framework/components/AButton/AButton.scss
- framework/components/AButtonGroup/AButtonGroup.scss
- framework/styles/theme/default.scss
- framework/styles/theme/dusk.scss
- framework/styles/utilities/palette.scss
Resolves #459 
made a guess at the focus-visible colors for dark theme, since that isn't reflected in the latest figma. The box shadow depth matches the other component set
Focused single button
"One" is focused:
the box-shadow for :focus-visible does not work well on button groups, so copied in the secondary button focus style
> Add focus-visible to AButton; Add focus to AButtonGroup buttons

- framework/components/AMultiSelect/AMultiSelect.js
- framework/utils/helpers.js
Resolves #472
Adds a `localeIncludes` method for filtering/searching by substring, which handles capitalization and accents
> fix: locale search filter for AMultiSelect

- framework/hooks/useFocusTrap/useFocusTrap.cy.js
- framework/hooks/useFocusTrap/useFocusTrap.js
- framework/utils/helpers.cy.js
- framework/utils/helpers.js
* Closes #482 
* Closes #486
This preserves sequential tab order for components calling `useFocusTrap` with an override on the element that should be initially focused to.
When a developer passes an element to set initial focus to within the focus trap, the tab order gets reset to the beginning of the trap on the next sequent `Tab` keydown.
Preserves tab order in situations where a developer passes `null` or a React ref to the `autoFocusElementRef`
No
> fix(useFocusTrap): preserve sequential tab order when initially focused element is overridden

- framework/components/ACheckbox/ACheckbox.js
> fix: remove extra classname

- framework/components/AStepper/AStep.js
- framework/components/AStepper/AStepTitle.js
- framework/components/AStepper/AStepper.js
- framework/components/AStepper/AStepper.mdx
- framework/components/AStepper/AStepper.scss
- framework/styles/theme/default.scss
- framework/styles/theme/dusk.scss
- framework/utils/hooks.js
**Closes #480 - Updates to `AStepper` to magnetic design**  
The goal was to limit breaking changes to visual only which required some extra complexity. The benefit to this however is that no changes to props or functionality are introduced for developers.
**Updates include**
- Horizontal layout restructure
- Magnetic color/theme adjustments
- Vertical theme alignment and minor layout updates
- Icon size and checkmark updates
**Responsive**
Handles small mobile screen
Handles unreasonably ultra wide screen
**In Modal**
Vertical style updates
> feat: stepper to magnetic design

- cypress/support/commands.js
- framework/components/ADataTable/ADataTable.cy.js
- framework/components/ADataTable/ADataTable.js
- framework/components/ADataTable/ADataTable.mdx
- framework/components/ADataTable/ADataTable.scss
- framework/hooks/useEscapeKeydown/useEscapeKeydown.js
- framework/hooks/useKeydown/useKeydown.cy.js
- framework/hooks/useKeydown/useKeydown.js
- framework/hooks/useKeydown/useKeydown.mdx
- framework/index.js
New feature witch supports: [#1157](https://github.com/advthreat/incident-manager/issues/1157)
There is no such feature.
Adds support for moving in ADataTable using arrow up/down keys.
No. It should be backward compatible. Only using new property enables it.
> ADataTable arrow up/down keys support

- framework/components/ADrawer/ADrawer.js
- framework/components/ADrawer/ADrawer.mdx
- framework/components/ADrawer/ADrawer.scss
- framework/components/ADrawer/ADrawerBody.js
- framework/components/ADrawer/ADrawerBody.scss
- framework/components/ADrawer/ADrawerFooter.js
- framework/components/ADrawer/ADrawerFooter.scss
- framework/components/ADrawer/ADrawerHeader.js
- framework/components/ADrawer/ADrawerHeader.scss
- framework/components/ADrawer/ADrawerSubtitle.js
- framework/components/ADrawer/ADrawerSubtitle.scss
- framework/components/ADrawer/ADrawerTitle.js
- framework/components/ADrawer/ADrawerTitle.scss
- framework/components/ADrawer/index.js
- framework/index.js
Resolves #304
Adds composable components for `ADrawer`
- ADrawerHeader
- ADrawerTitle
- ADrawerSubtitle
- ADrawerBody
- ADrawerFooter
Issues resolved:
- auto content scrolling
- title text won't overlap close X button
- footer defaults to box shadow as per design, but has a `divider` option to swap back to the current style
@sabrinamokerji fyi
> feat: Add composable drawer components

- framework/components/ACheckbox/ACheckbox.js
- framework/components/ACheckbox/ACheckbox.mdx
The checked state was not updating correctly when the "space" or "enter" key was pressed while a noLabel checkbox was focused
> Fix no label ACheckbox keydown check event handler

- framework/components/ADataTable/ADataTable.js
- framework/hooks/useEscapeKeydown/useEscapeKeydown.js
fix #503
I confirmed locally by copying freshly built `lib` into our project that the test pass then.
> fix: avoid potential cyclic import in Jest

- framework/components/ADataTable/ADataTable.js
> fix: replace `toSorted` by explicit copy of the array

- framework/components/AButton/AButton.scss
**Resolves #516 - Override conflicting color**
This only appears to be an issue once deployed as I could not reproduce on local dev or in magna playground.  This is a quick fix to the stylesheets, but the lengthier fix is combing through `mds-light-theme` and `mds-dark-theme` to update all the colors causing potential conflicts.  Those color definitions are likely outdated by now, but it is still used for theming so it would require time to find and test what the impacts are with either removing unused colors or updating...
> fix: override conflicting theme

- framework/components/AApp/base/color-helpers.scss
- framework/components/ACheckbox/ACheckbox.js
- framework/components/ACheckbox/ACheckbox.scss
- framework/styles/theme/default.scss
Resolves #529
- Magnetized the checkbox svg paths
- Use div+css style for unchekced state
- Standardized viewBox size
- Retained custom colors
- Retained validation states
- Updated disabled checked/intermediate state to match magnetic design
> Rework checkbox to be more magnetic; fix size

- framework/components/ATabs/ATabs.scss
Causes issues in tabs that are wrappered, such as ones with `<a>`.
> Remove first and last of type margin override

- framework/components/ACheckbox/ACheckbox.js
- framework/components/ACheckbox/ACheckbox.scss
Conflicts with old styles, and isn't necessary anymore I think
--------
Should darken on hover for default, warning, and danger checkboxes - default darkens on hover for magnetic. Should lighten on custom closers - no magnetic equivalent and this keeps it non breaking
> remove color css on checkbox

- framework/utils/hooks.js
Resolves #540 
My guess is there's a timing issue with the `.disconnect()` call running after React has already gotten rid of the DOM node that the ref is pointing to.. null checking should avoid the error
> Check current ref in resize observer callback

- framework/components/AToast/AToast.js
- framework/components/AToaster/AToastPlate.js
- framework/components/AToaster/AToaster.scss
- framework/components/AToaster/useAToaster.js
Magnetic says toasts should go in the upper right, "24px inset below the header and right edge of the browser window."
Before
After
Note that the top offset accounts for the 56px of the XDR header, so it looks a bit off on the magna site
> Default toast placement to upper right

- framework/components/AMultiSelect/AMultiSelect.cy.js
- framework/components/AMultiSelect/AMultiSelect.js
- framework/components/AMultiSelect/AMultiSelect.mdx
- framework/components/AMultiSelect/AMultiSelect.scss
- framework/components/AMultiSelect/AMultiSelectCounter.js
**Resolves #521 - Create multiselect counter and set as default.**
- Adds a `withTags` prop to multiselect to differentiate tags or counter inputs. 
- Menu list items for multiselects are now checkbox only.  Single select list items remain the same (right aligned checkmark).
**Resources:**
**Magnetic: single and multiselects** - https://magnetic.cisco.com/0a43ab5cd/v/0/p/42131c-select
**Figma** - https://www.figma.com/file/oVZWatImEIbl1c8sjdGxi0/%F0%9F%A7%B2--Magnetic-Design-Library?type=design&node-id=12394-50157&mode=design&t=vRcHv5Zi8JmJw0dV-0
> feat: counter multiselect

- framework/components/ATag/ATag.cy.js
- framework/components/ATag/ATag.js
- framework/components/ATag/ATag.mdx
- framework/components/ATag/ATag.scss
**Resolves #535 - Variant tags are now interchangeable, option for custom icons**
**Design updates:**
- Binary icon and spacing updates - removes need for radio button differences 
- CSS refactor to make binary and status interchangeable 
**Feature request:**
- Option for custom icons in tag variants
**Before:**
**After**
> refactor: tag updates

- framework/components/AMultiSelect/AMultiSelect.js
- framework/components/AMultiSelect/AMultiSelect.scss
**Fixes #544 - Clear button overlap** 
**Fixes include:**
- The scroll class was not updating appropriately after onSelect changes.  This was fixed by moving the element checks into a useEffect and tying in the onSelect behavior to react state for real time dimension updates.  
- The elements used to calculate the scroll overflow have been also adjusted for greater accuracy.
- Style updates to large and small input heights
**Demo** 
-Scrollbar appears at the right time
-Very long tags do not overflow clear button
> fix: scroll state

- framework/components/ACombobox/ACombobox.js
- framework/components/ACombobox/ACombobox.mdx
Introduces equivalent changes from https://github.com/cisco-sbg-ui/atomic-react/pull/1178, but for the `ACombobox` component.
When `ACombobox` has a large number of items, it spans the entire viewport:
Adds a `maxHeight` prop that can be configured to add a scrolling container to the menu items:
No
> feat(ACombobox): allow dropdown menu to be scrollable with "maxHeight" prop

- .github/workflows/beta.yml
> Bump workflow npm-publish to use v2

- framework/components/ADataTable/ADataTable.cy.js
- framework/components/ADataTable/ADataTable.js
- framework/components/ADataTable/ADataTable.mdx
- framework/components/ADataTable/ADataTableCell.js
- framework/components/ADataTable/ADataTableCellTemplate.js
- framework/components/ADataTable/ADataTableHeader.js
- framework/components/ADataTable/ADataTableHeaderTemplate.js
- framework/components/ADataTable/ADataTableRow.js
- framework/components/ADataTable/ADataTableRowTemplate.js
- framework/components/ADataTable/ADataTableWrapper.js
- framework/components/ADataTable/useKeyboardNavigation.js
- supports: [#2047](https://github.com/advthreat/incident-manager/issues/2047)
- be able to add attributes which will be rendered on header elements
- split very complex ADataTable code to logical components which should help when adding new features
**What is the current behavior?**
- there is no possibility to pass any attribute to ADataTableHeader level.
- we can add properties which are used while rendering ADataTableHeader elements.
- no, this feature was created to maintain backward compatibility
> feature: ADataTable takes header properties and pass them to ADataTableHeader ("td") element

- framework/components/AList/AList.scss
Closes #588 - Decouple styling
Seems like this might take care of it.
> fix: add identifier

- framework/components/AInputBase/AInputBase.js
- framework/components/AInputBase/AInputBase.scss
- framework/components/ATextInput/ATextInput.cy.js
- framework/components/ATextInput/ATextInput.js
- framework/components/ATextInput/ATextInput.mdx
- framework/components/ATextInput/ATextInput.scss
Resolves #594 
Also fixes padding issues inside the input (always added `append` to AInputBase, causing scss from ATextInput.scss to have padding 0)
> Add generic prepend and append content to ATextInput

- framework/components/ATriggerTooltip/ATriggerTooltip.js
Resolves #597 - **Allow tooltip trigger on webclamp**
> fix: allow tooltip trigger on webclamp

- framework/components/AAccordion/AAccordion.scss
**Resolves #602 - Overflow fix**
Raj noted they tried to override the overflow, but it impacted the animation.  I compared both with and without and didn't see any differing animation, but its worth more testing.
> fix: menu overflow

- framework/components/AInlineInputBase/AInlineInputBase.js
Allows for custom display value when not editing in `AInlineTextInput` and `AInlineTextarea`. For example, using a markdown renderer
> Add displayValue prop to inline inputs

- framework/components/AAutocomplete/AAutocomplete.js
- framework/components/AButtonGroup/AButtonGroup.js
- framework/components/ACombobox/ACombobox.js
- framework/components/AFieldBase/AFieldBase.cy.js
- framework/components/AFieldBase/AFieldBase.js
- framework/components/AFieldBase/AFieldBase.mdx
- framework/components/AInputBase/AInputBase.js
- framework/components/AMultiSelect/AMultiSelect.js
- framework/components/ASelect/ASelect.js
- framework/components/ASlider/ASlider.js
- framework/components/ATextInput/ATextInput.js
- framework/components/ATextarea/ATextarea.js
**Please check if the PR fullfills these requirements**
UX needs from us to display field hint and optionally display error message - but keeps hint visible (see screenshot). This was not possible to reach with "hint" and "rules" because "rules" needs validation and validation needs user interaction. But we need to control both properties from outside because we are using external validation framework.
I am adding new property "hints" allowing me to put one or more hints to "AFieldBase" and related components.  Every hint can be configurable, we can set alarm level, we can hide it when validation error occur, we can infer component validation status. I kept there original "hint" for backward compatibility and marked it as deprecated. I also …
> feat: field base can have multiple hints

- framework/components/AButton/AButton.scss
```
<AButton  href="https://www.cisco.com">
Launch Cisco.com
</AButton>
```
> Fix text color for AButton with href in primary

- framework/components/AAccordion/AAccordion.mdx
- framework/components/AAccordion/AAccordion.scss
- framework/components/AAccordion/AAccordionHeaderTitle.js
Enables to configure placement of `AAccordionHeaderTitle` icon. Now we have way to place it also to the left side.
We verified with UX that they really would like to have it left.
Supports [#1539](https://github.com/advthreat/incident-manager/issues/1539)
**What is the current behavior?**
Currently we are able to place the icon only to the right side.
No this change is backward compatible.
> feature: accordion title has now way to place chevron icon to the left

- framework/components/APageLayout/APageAlert.js
- framework/components/APageLayout/APageAlert.scss
- framework/components/APageLayout/APageLayout.mdx
- framework/components/APageLayout/index.js
- framework/index.js
I was recently given a design to render a page level alert:
<details>
<summary>Screenshot of redacted wireframe</summary>
</details>
I figured instead of doing something locally to the application was requested for, I'd make it part of the "APageLayout" family, especially considering it looks to be part of the [Magnetic "Page title" component specs](https://www.figma.com/file/oVZWatImEIbl1c8sjdGxi0/%F0%9F%A7%B2--Magnetic-Design-Library?type=design&node-id=14757-56953&mode=design&t=kNl71JpX4k6zGpRm-0):
* Adds an `APageAlert` component
* This component is a wrapper around `AToast` with some style overrides and spacing
1. Navigate to the [Advanced Usage](https://magna-react-git-feat-a-page-alert.securex-preview.app/components/pagelayout#advanced-usage) Page Layout documentation
2. Verify …
> feat: add `APageAlert` component

- framework/components/ATimeline/ATimeline.scss
**Fixes #632 - Lower z-index**
I couldn't find a reason why these were set so high to begin with, but was able to lower them without any obvious consequence.  Tested on IM and Shell.
Also added a slight px adjustment to line which was slightly off in other envs:
**Before:**
**After:**
> fix: lower z-index

- framework/components/AButton/AButton.scss
Resolves #636 
Seems like this was leftover to account for buttons with anchor tag, but that has been adjusted elsewhere
> remove important from secondary text color

- framework/components/ADrawer/ADrawer.js
- framework/components/ADrawer/ADrawer.mdx
- framework/components/ADrawer/ADrawer.scss
- framework/components/ADrawer/ADrawerTitle.js
- framework/components/AModal/AModal.cy.js
- framework/components/AModal/AModal.js
- framework/components/AModal/AModal.mdx
- framework/hooks/useOutsideClick/useOutsideClick.js
- framework/hooks/usePopupQuickExit/usePopupQuickExit.js
- framework/hooks/useReturnFocusOnClose/useReturnFocusOnClose.js
Closes  #627 
The current behavior is outlined in the issue here - #627 
When closing modals and drawers, the focus should return to whatever element was used to them. Also, they should be able to be closed upon pressing the "Escape" key, provided that an "onClose" function is passed into their props. The usePopupQuickExit hook is utilized to give these components this ability out of the box. 
Although not a breaking change, an onClose function to both Modals and Drawers. 
> fix-627 Add accessibility features to modals and drawers

- framework/components/AInlineInputBase/AInlineInputBase.scss
- framework/components/ASelect/ASelect.scss
- framework/components/ATextInput/ATextInput.scss
Align to `--base-text-weak-default`
Affects `ASelect`, `ATextInput`, and all inputs using `AInputBase`
> Align placeholder colors

- framework/components/ATriggerTooltip/ATriggerTooltip.js
Accessibility
> The tooltip should appear on focus or when the element is hovered on, without additional interaction. It should disappear automatically when the focus on the owning element is lost or the mouse is moved outside the owning element and the tooltip. While the tooltip does not receive focus, the Escape should close it if it is open.
Only applies to `ATriggerTooltip`
> Show tooltip on focusin; close on escape

- framework/components/AEmptyState/AEmptyState.js
- framework/components/AModal/AModal.js
related issue https://github.com/advthreat/incident-manager/issues/2432
updating PropTypes of following components to get rid of warning messages in the console
- `AEmptyState`
- `AModal`
On the `AModal` component the propType definition of the `autoFocusElementRef` was not correct. It was always complaining when the `autoFocusElementRef` property was set to non nullable value
On the `AEmptyState` the propTape definition is correct (but maybe to strict?). Currently it allows to fill in only string value into the `message` property. In incident manager there are several usages where react element is passed into this property, mainly to split the error …
> chore: updating PropTypes to clean up console warning

- framework/components/AIcon/AIcon.js
If the icon isn't in the magna icons map and it gets to the `kebabify` check, an empty string will crash the component.
Adds a safety check for good measure
> Add a null check for icon name

- framework/components/ADrawer/ADrawer.js
- framework/components/ADrawer/ADrawer.scss
- framework/components/AModal/AModal.js
Removes new `a-drawer-content` container
> Switch refs for modal accessibility tracking

- framework/components/AAlert/AAlert.scss
The markdown pages on the demo site seem to add a `<p>` tag to the AAlert message content when used outside the Playground. This causes the alignment in alerts to be a bit off
> Remove padding from p tags in AAlert

- framework/components/ACheckbox/ACheckbox.js
When using without a label, the wrapper has a tabIndex for focus, along with the `<input>`. This causes two separate focus states when tabbing through.
> Fix double focus for checkboxes with no label

- framework/hooks/useFocusTrap/useFocusTrap.js
In cases such as virtualized lists that update dynamically, the next node from the TreeWalker may no longer exist in the DOM. The memory reference still points to the object, and since the reference holds onto it the object isn't nulled out. However, the node may be detached. In this case the `tab` key stops working, since there is no previous or next node for it to move to. 
As a safety, when the next node to focus is no longer in the DOM, fallback to refocus to `rootRef` element.
> Safety fallback useFocusTrap when node is no longer in the DOM

- framework/components/ADataTable/ADataTable.mdx
- framework/components/ADataTable/ADataTable.scss
- framework/components/ADataTable/ADataTableCellTemplate.js
- framework/components/ADataTable/ADataTableHeader.js
- framework/components/ADataTable/ADataTableHeaderTemplate.js
- framework/components/ADataTable/ADataTableRowTemplate.js
**Closes #656 - col width small option**
Give option for columns that need smallest width possible. Ideal for icons, small tags, checkboxes etc.
`colWidthSm: true`
> feat: col width small option

- pages/[[...route]]/index.scss
row height auto doesn't work when deployed...
> Fix docs header height in grid

- docs/Sidebar.js
This renders the `ADrawerTitle` component in the mobile navigation drawer. It also renders the drawer *with* transitions to mimic a more "magnetic" experience for what we do in our apps today.
> docs: use ADrawerTitle in mobile navigation sidebar drawer and restore transitions

- pages/[[...route]]/index.js
One day, a developer is going to be *really* confused why writing "success" in a blockquote is rendering a success variant `AAlert` component. This will reinforce the pattern of wrapping the desired variants in colons, .e.g., `:success:`
> docs: refine success alert criteria rendered for markdown blockquote

- framework/components/AKeyValue/AKeyValue.js
It's valid for the value field to be blank
> Don't require a child in AKeyValue

- framework/components/ACopyButton/ACopyButton.js
- framework/components/ATriggerTooltip/ATriggerTooltip.js
Resolves #693 
Refactored ACopyButon to separate out the tooltips and not rely on timing. The "Copied" tooltip will disappear when the mouse moves off the trigger element, which is a more expected behavior.
>  Add prop for copy button timeout; change default timeout

- framework/components/ADrawer/ADrawer.js
- framework/components/ADrawer/ADrawer.mdx
- framework/components/ADrawer/hooks.js
- framework/components/ADrawer/index.js
- framework/index.js
- framework/utils/hooks.js
Adds a hook for easy Magnetic drawer slide out and back in when changing objects - for single "render" if `ADrawer` where only the content changes on open. 
This will help keep drawer transitions consistent where a global transition context isn't used.
> useDrawerToggle for slide out->in animation

- framework/components/AAlert/AAlert.scss
Figma has the icon aligned vertically centered
> Align AAlert dismiss icon

- framework/changelog.mdx
- framework/components/ATabs/ATab.cy.js
- framework/components/ATabs/ATab.js
- framework/components/ATabs/ATabGroup.js
- framework/components/ATabs/ATabs.mdx
- framework/components/ATabs/ATabs.scss
- framework/components/ATabs/OverflowMenuTab.js
Builds off the ideas in https://github.com/cisco-sbg-ui/magna-react/pull/650
The previous implementation lacked a way to track focus and selected state simultaneously. This made it difficult to configure the keyboard arrows to not automatically select a tab (not desired when the panel content may take time to load). Additionally it made it difficult to avoid opening link tabs in the auto-select mode while tracking the other states.
> Refactor tab selected tracking; add arrow key accessibility

- framework/changelog.mdx
- framework/components/AApp/AApp.mdx
- framework/components/ABreakpoint/ABreakpoint.spec.js
- framework/components/ABreakpoint/index.js
- framework/hooks/useABreakpoint/index.js
- framework/hooks/useABreakpoint/useABreakpoint.js
- framework/hooks/useABreakpoint/useABreakpoint.mdx
- framework/index.js
- framework/styles/utilities/variables.scss
Resolves #671 
This updates the breakpoints to magnetic spec, and exports them as an object for use outside of the hook. Docs have been updated as well under `/hooks/use-a-breakpoint`
@sabrinamokerji fyi
This is a breaking change, so will go into magna 2.0
> Update breakpoints to magnetic spec; move code into hooks

- framework/components/AActivityTimeline/AActivityTimelineItem.js
- framework/components/AActivityTimeline/components/AActivityTimelineListItem.js
Closes #720 
* #720 
* Spreads props coming into the "AActivityTimelineItem" component from a developer
* I also explicitly added the `className` as its own prop to make it more clear to a reader of the component that it does take `className` as a prop (so that they don't have to make an assumption that it would be passed down via spread instead)
1. Copy the following code snippet:
```jsx
<AActivityTimeline>
<AActivityTimelineItem
data-testid="TimelineItem"
time="2022-02-12 21:11:10 UTC"
title="Account Created"
/>
</AActivityTimeline>
```
2. [Go to the `AActivityTimeline` documentation page for the preview branch](https://magna-react.vercel.app/components/activity-timeline)
3. Paste the code you copied from step 1 into any playground editor
4. Inspect the browser for the playground …
> fix: spread props in `AActivityTimelineItem` component

- framework/components/AAccordion/AAccordion.scss
This reverts commit d50888d24320ded92e2fc772930b61450e11d1ed
https://github.com/cisco-sbg-ui/magna-react/commit/d50888d24320ded92e2fc772930b61450e11d1ed
`overflow: hidden` seems to break ASelect menu when inside of an accordion
Reverting for now
> Revert "fix: accordian transition"

- cypress/support/commands.js
- framework/components/AActivityTimeline/AActivityTimeline.cy.js
- framework/components/AActivityTimeline/AActivityTimeline.mdx
- framework/components/AActivityTimeline/AActivityTimeline.scss
- framework/components/AActivityTimeline/AActivityTimelineItem.js
- framework/components/AActivityTimeline/components/AActivityTimelineListItem.js
When timeline items are rendered from a paginated source of data, it is possible (and likely) that the very last item in the user's current view is *not* the very last item in the source of data. In such cases, the vertical "connector" rendered underneath the timeline *should* be rendered. However, given the current implementation, the connector would be hidden since it is the last list item in the DOM.
This PR solves this issue by allowing a developer to pass a `withConnector` prop to control the connector's visibility.
(Please see [preview branch "Paginated List" example](https://magna-react-git-feat-timeline-item-connector-prop.securex-preview.app/components/activity-timeline) for more context)
* Adds a `withConnector` prop to the `AActivityTimelineItem` component
* Adds documentation …
> feat(AActivityTimeline): allow timeline item connector visibility to be controlled with prop

- .github/workflows/beta.yml
- .github/workflows/ci.yml
Seems there's an issue with the node version on the action runner causing npm ci to fail. This works around it for now
> change to node 18.19 to workaround node issue on the action runner

- .github/workflows/beta.yml
- .github/workflows/ci.yml
- .github/workflows/woke.yml
Gets rid of the node 16 deprecation warning in the actions log
> Bump node actions in ci

- framework/components/AApp/base/links.scss
- framework/components/ATabs/ATab.js
- framework/components/ATabs/ATabGroup.js
- framework/components/ATabs/ATabs.scss
- framework/utils/helpers.js
When the ATab is a router element, the onClick functionality isn't actually what controls the route change - so proxy click the item in the more menu to run the router's logic.
Color causes issues with tabs that set an `<a>` element as the component for a tab
> proxy click router component as tab; don't style links at a global level for tabs

- framework/components/AAccordion/AAccordion.mdx
- framework/components/AAccordion/AAccordion.scss
- height of element is now reduced to visible part when it is in collapsed state
Closes: #743
Now the `AAccordion` when collapse has height related to its headers. Body content does not enlarge element height now.
In "incident-manager" it fixes two places when `AAccordion` is used - "report tab" and "response tab".
Yes, this fixed behaviour could be breaking change.
> fix: AAccordionBody content hidden in collapsed state

- framework/components/AApp/base/typography.scss
- framework/components/AButton/AButton.scss
- framework/components/AToast/AToast.scss
- framework/components/ATooltip/ATooltip.scss
- framework/styles/utilities/variables.scss
Some places were using `$line-height`, which computes to `1.25`. This doesn't affect the css, without the `rem` added.
Make sure nothing was trying to use the raw number, vs the intended `rem` value
> Fix usage of line height variables

- framework/components/ADrawer/ADrawer.scss
Causes scroll on body element to now show otherwise
> span wrapper on ADrawer should have 100% height

- framework/utils/helpers.js
using `func.apply(this, ...)` causes the compilation in the lib build to generate `var _this = this;`. This isn't good practice, and causes warnings in some environments
> Use .call in debounce function

- framework/components/AButton/AButton.js
Closes #776 
When rendering `AButton`, passing the `component` prop simultaneously with the `href` prop ignores the `component` prop.
When rendering `AButton`, passing the `component` prop simultaneously with the `href` prop **does not** ignore the `component` prop.
No
> fix(`AButton`): do not ignore `component` prop when rendered with `href` prop

- framework/components/AAccordion/AAccordion.scss
- framework/components/ACard/ACard.scss
- framework/components/ADrawer/ADrawer.scss
- framework/components/AInputBase/AInputBase.scss
- framework/components/APagination/APagination.scss
- framework/components/ASimpleTable/ASimpleTable.scss
- framework/components/ATag/ATag.scss
- package-lock.json
- package.json
Resolves #781
New sass versions throw warnings about css rules being ordered after child groups and include/extend statements. Moving the CSS around to fit the standard.
> Move css rules to resolve deprecation warnings in ordering

- framework/components/AButton/AButton.js
- framework/components/AButton/AButton.mdx
- framework/components/AButton/AButton.scss
Should be centered inside the button container
> Remove margin right for spinner inside button

- framework/components/AMenuBase/AMenuBase.tsx
- framework/components/AMenuBase/hooks.js
- framework/components/AMenuBase/types.ts
- framework/components/ATooltip/ATooltip.tsx
- framework/components/ATooltip/types.ts
- framework/components/ATriggerTooltip/ATriggerTooltip.cy.js
- framework/components/ATriggerTooltip/ATriggerTooltip.mdx
Adds a hook, enabled on `ATooltip`, that checks the outer bounds for `AMenu` placement, and flips it it to the opposite if it would render out of bounds.
This only applies to the starting placement - top, right, bottom, left. It does not affect the secondary, in placements such as `top-right`.
> Add auto menu flip logic on bounds checking

- framework/components/AMultiSelect/AMultiSelect.js
- framework/components/AMultiSelect/AMultiSelectCounter.js
Resolves #797
Adds `counterTooltipProps` to `AMultiSelect`. This will pass the object through to the `ATooltip` component and spread it as props. This allows for setting a style and overriding the content
> 797 - Add tooltip prop pass through for the counter tag

- framework/components/ACheckbox/ACheckbox.js
- framework/components/ACombobox/ACombobox.js
- framework/components/AForm/AForm.js
- framework/components/AInputBase/AInputBase.js
- framework/components/AMultiSelect/AMultiSelect.cy.js
- framework/components/AMultiSelect/AMultiSelect.js
- framework/components/ASelect/ASelect.js
- framework/components/ASlider/ASlider.js
- framework/components/ASwitch/ASwitch.js
- framework/components/ATextInput/ATextInput.js
- framework/components/ATextarea/ATextarea.js
Fixes for #794 
Changes
- `AForm` will no longer validate disabled fields. 
- `AForm` will reset the validation state if a field becomes disabled and the form is re-validated
- `AMultiSelect` now validates `required` as non-empty value AND non-empty array. Array is the only valid type for the `value`
- `ASelect` will be properly reset when reset function is called
> 794 - don't validate disabled fields in forms; validate required empty array for multiselects

- framework/components/ASelect/ASelect.js
- framework/utils/hooks.js
onSelected is getting called on select menu open
was called to reset value when AForm called reset. But reset gets called when the select is opened. Will investigate a different solution to proper resetting, this will fix the issue for now
> ASelect don't fire onSelected when resetting

- framework/components/ADrawer/ADrawer.js
Resolves #803 
Non-modal drawers (`asModal={false}`) weren't getting the `usePopupQuickExit` functionality from `AModal`.
> 803 - add popup quick exit for non modal drawers

- framework/components/AAutocomplete/AAutocomplete.js
- framework/components/AButtonGroup/AButtonGroup.js
- framework/components/ACombobox/ACombobox.js
- framework/components/AInputBase/AInputBase.js
- framework/components/AMultiSelect/AMultiSelect.js
- framework/components/ASelect/ASelect.js
- framework/components/ASlider/ASlider.js
- framework/components/ATextarea/ATextarea.js
- Syncs hints to accept string/node everywhere
- Resolves "Warning: Received `true` for a non-boolean attribute `medium`."
> Sync hints prop types across componnets; fix medium warning for AInputBase

- framework/components/AMenuBase/AMenuBase.tsx
- framework/components/AModal/AModal.mdx
- framework/utils/helpers.js
- framework/utils/hooks.js
Resolves #794 
Adds a scroll detection hook, and recalculates menu position when any container is scrolled iff the menu is open.
The handler to recalculate position is throttled to 60fps on window animation frame to reduce the amount of rerenders
> Reposition open menus on scroll of a container

- framework/components/ADrawer/hooks.js
Now that ADrawer gets that hook in both modal and non modal cases, no need to have it in the transition hook
> Remove redundant usePopupQuickExit in drawer hook

- tsconfig.json
**Goal:** This will allow groups to use the types we have now, while also supporting old js files that we have.
**Problem:** Typescript libraries that consume our library are reading d.ts files for components we haven't changed over yet.  (this is non issue in js libraries using our typescript library however).
**Solution:**
This change aims to `skip` over components that aren't ready to be "read" by other libraries.  However, the catch is components will result in "any" in other typescript libraries so they will need to temporarily enable:
**`"noImplicitAny": false,`**
while we work through this transition.
Note: None of our typescript changes impact the IM team as they have their own magna types they use for the time being.
> fix: skip .js files from d.ts generation for ts libraries

- framework/components/ADrawer/ADrawer.js
Disables click outside functionality by default, which is the same as `AModal`
> Respect closeOnOutsideClick prop simimilar to AModal

- framework/components/ADrawer/ADrawer.js
Pass the `closeOnOutside` click to the ref so it doesn't affect the escape key to close hook
> Fix instantiation of usePopupQuickExit in drawer

- tsconfig.json
Not sure how this was ever working without this.  This will hopefully help referencing issues in jest tests.
> fix: add back in indexd

- framework/components/ADrawer/ADrawer.js
- framework/components/ADrawer/hooks.js
- framework/hooks/usePopupQuickExit/usePopupQuickExit.d.ts
- framework/hooks/usePopupQuickExit/usePopupQuickExit.ts
usePopupQuickExit seems to cause conflicts with existing custom slide in/out controllers for ADrawer. 
Reduce the scope down to just handle escape for accessibility, and let products handle focus accessibility on their own if they aren't using `useDrawerToggle`
> Use useEscapeKeyDown for drawer

- framework/components/AAlert/AAlert.tsx
Resolves  #825 
Issue was due to backwards compatibility we are setting both to true so either one would always be true.
> fix: dismissible v dismissable logic

- framework/components/AMenuBase/AMenuBase.tsx
Previously the code used `appCoords.scrollLeft` and `appCoords.scrollTop` to calculate offsets of the wrapper when not using `withNewWrappingContext`. 
However, both of those values would always be undefined, as they aren't part of `DOMRect`.
This caused every `AMount` container without `offsetParent` of `document.body` to use undefined values in the offset calculation. This led to the values always computing to `NaN`.
The values being used were changed in https://github.com/cisco-sbg-ui/magna-react/pull/773/files#diff-bcc8104da7921ce69a5415f3862dc9c690e7515fee36da98867d8bec28feae41R148
By changing `appCoords.scrollLeft` and `appCoords.scrollTop` to `appCoords.left` and `appCoords.top`, the calculations started working, but were using values that were often positioned relative to the page …
> Remove logic around scrollLeft/scrollTop for menu placement

- package-lock.json
- package.json
Might resolve connection timeout issues, but it doesn't look like it'll resolve intermittent test failures when bundles load
https://docs.cypress.io/guides/references/changelog#13-13-1
> dep: bump cypress to 13.13.2

- framework/components/AProgressbar/AProgressbar.mdx
- framework/components/AProgressbar/AProgressbar.scss
- framework/components/AProgressbar/AProgressbar.tsx
- framework/components/AProgressbar/types.ts
- Takes in node for label for `<Trans />` translation
- ROUNDS percentages, not sure how we got away with that all this time.
- Set styles on texts so they don't inherit
- Makes sure zero shows percentage sign as well.
> fix: Stray progressbar fixes

- framework/components/AEmptyState/AEmptyState.js
- framework/components/AEmptyState/AEmptyState.mdx
- framework/components/AEmptyState/AEmptyState.scss
- framework/components/AEmptyState/types.ts
Not including `info` in prop list was causing issues in TS repos.  Fixed up mdx and added notes on variant deprecations, however this is still backwards compatible.
> fix: add info and adjust mdx to latest figma

- framework/components/ATag/ATag.js
@rwharrisjr re: @mvelkCisco response in https://github.com/cisco-sbg-ui/magna-react/pull/851#issuecomment-2316997714
Adding back the .js file now for rendering and docs generation while we work on this more.  Tsx can stay so types get picked up at least.  If there were any changes added in the `ATag.tsx` they will also need to get added to this `ATag.js` as it is the previous version of what went out in and due to file change was unable to get a diff:
https://github.com/cisco-sbg-ui/magna-react/pull/848
https://github.com/cisco-sbg-ui/magna-react/pull/851
> chore: add back .js file

- framework/components/ATag/ATag.js
- framework/components/ATag/ATag.mdx
- framework/components/ATag/ATag.scss
- framework/components/ATag/ATag.tsx
- framework/components/ATag/types.ts
- Adds the standard button control focus/hover states to "interactive" tags
- Adds `hideStatusIcon` prop so tags like info/disabled can be used in more contexts 
- Fixes hover border-radius on interactive tags
@wlorand3 fyi
> Tag focus/hover fixes; hideStatusIcon prop

- next.config.js
- tsconfig.next.json
This should keep tsconfig.json from getting overwritten when we start the dev server
> Let next have its own tsconfig file

- framework/components/AButton/AButton.js
- framework/components/AButton/AButton.mdx
- framework/components/AButton/AButton.scss
- framework/components/AButton/types.ts
- framework/components/AContextualNotificationMenu/AContextualNotificationMenu.scss
- framework/components/APanel/APanel.scss
- framework/components/APopover/APopover.scss
- framework/components/ATheme/ATheme.scss
- framework/styles/utilities/mixins.scss
- framework/styles/utilities/variables.scss
**Resolves #868 Adds Floating button variant, fixes various style updates**
1) **Floating button**
2) **Adds new dark mode box shadow**
3)  **Fixes Icon button widths and fixed margin that was still applying to icon btns**
Before
After
> feat: add floating btn style, fix various styles and shadows across app

- framework/components/ATabs/ATabGroup.js
- framework/components/ATabs/ATabs.scss
If tab n+1 is smaller than tab n, and tab n overflows but tab n+1 doesn't, n+1 can show and cause the list to be out of order
> Stop checking tab overflow once overflow is hit

- framework/components/AFloatingMenu/useFloatingDropdown.tsx
- framework/components/AMultiSelect/AMultiSelect.js
**Before**
Menu stays closed when no items present
**After**
> fix: allow empty display

- framework/components/ATabs/ATab.cy.js
I think this stems from ATab setting the selected tab state in a useEffect, which would take place after the initial render. My guess is cypress is running leftArrow type command before that state has been set, so no tab is actually focused at the start.
Added a check that should retry and wait until there is a selected/focused tab available to navigate from
> Attempt at fixing flakey tab test

- framework/components/ATabs/ATab.cy.js
CI tests are passing with updated a-tab test from #891, however the test could be more succinct. Seeing if this works as well
> chore: alternative to the alternative a tab test

- framework/components/ATabs/ATab.cy.js
In this 15th test refactor, this replicates an actual action a user would take to get into a tab group which would be by tabbing into the group.  One we are "tabbed" in we verify that it is actually focused.
> refactor: one more tab fix

- framework/components/ACopyButton/ACopyButton.js
https://github.com/cisco-sbg-ui/magna-react/commit/d17d584bc8a669eeedec41d7610f222f59489770#diff-966cc622ccfa356f0b786b6d2e927430f02cf877c24b3878c30b5879a152cb9cR149
Not sure what else that may break
> ACopyButton - Don't apply button icon style when there's text

- framework/components/ATabs/ATab.cy.js
Have cypress stay active on element rather than re-getting.
> fix: tab test again

- framework/components/AInputBase/AInputBase.scss
```
<AInputBase
append="[Append]"
prepend="[Prepend]"
className="mb-3"
clearable
readOnly
disabled
onClear={() => alert("cleared")}
label="Label - Focused"
hints="This is a sample of hint text below a form input"
focused
>
[Children]
</AInputBase>
```
Try on Extend -> Input Base. Note the input's background color. Disabled should gray it out even if `readOnly` is set
> Input disabled state should take precendence over readOnly

- framework/components/AEmptyState/AEmptyState.js
- framework/components/AEmptyState/AEmptyState.scss
- framework/components/AEmptyState/types.ts
Adds positive/negative classes to the dom for corresponding variants, marks in code as deprecated as a reminder to clean up for next major version
> Sync classes for AEmptyState variants with magnetic

- framework/components/AFloatingMenu/useFloatingDropdown.tsx
This was not the cause of test cases failing. 
This feature allows the menu to hide when the anchor is scrolled out of view. In theory UI test cases will have the anchor in view, and rarely cover scroll scenarios, so this change should be safe.
> Re-enable isReferenceHidden check

- framework/components/AMultiSelect/AMultiSelect.scss
In some envs if another component brings in the a-field-base css due to loader order, this can get overridden. Increasing specificity should help
> Add extra specificity for multiselect width unset

- framework/components/AEmptyState/AEmptyState.js
- framework/components/AEmptyState/AEmptyState.mdx
- framework/components/AEmptyState/AEmptyState.scss
- framework/components/AEmptyState/types.ts
Magnetic figma shows smaller icon sizes and a larger gap under the label. Note this does not align with current CDS implementation, but is less comically large than before.
> Add AEmptyState horizontal layout; align magnetic small/medium/large sizes

- framework/components/ATabs/ATab.cy.js
- framework/components/ATabs/ATabGroup.js
Use a ref as a backup to track focused element, for when rendering doesn't trigger immediately
> Fix the tab keyboard navigation initialization and test case

- framework/components/AInputBase/AInputBase.scss
This fixes an issue spotted in an Incident Manager PR: https://github.com/advthreat/incident-manager/pull/3009#issuecomment-2427565813
When the `AInput` is narrower (< 220px), it eventually makes the "close" button shrink.
Before fix:
After fix:
> fix flex spacing properties

- framework/components/ATriggerBase/ATriggerBase.tsx
- framework/components/ATriggerBase/types.ts
- framework/components/ATriggerTooltip/ATriggerTooltip.mdx
- framework/hooks/useToggle/useToggle.d.ts
- framework/hooks/useToggle/useToggle.js
•	[-] This change has been integrated and tested against 2 out of 3 typescript applications
•	[-] This change passed unit tests in these applications
•	[x] The changes are documented in component docs and changelog
•	[-] The ESLint plugin has been updated if a new component is added
•	[-] Test have been added or modified, if appropriate
• [-] Convert component to tsx, if reasonable
Usage, with a delay for cases such as telemetry 
```js
onShow={({tooltipRef}) => {
// Only fire if it's been open for 1 second
return setTimeout(() => {
if (!tooltipRef?.current) {
return;
}
console.log("Tooltip has been open for over a second");
}, 1000);
}}
onHide={() => {
console.log("Tooltip has been hidden");
}}
```
Note that …
> Add onShow/onHide callbacks for ATriggerTooltip

- framework/components/AIcon/AIcon.mdx
- framework/components/AIcon/AIcon.scss
- framework/components/AIcon/AIcon.tsx
- framework/components/AIcon/types.ts
Added back string sizing option as this was being used in IM and caused breaking change.  Updated the sizes to _reasonable_ values as `48px` is gargantuan as a default large.
> fix: add back string sizing in AIcon

- framework/components/ASimpleTable/ASimpleTable.scss
This came up due to tags blending in with the background of the hover color in dark mode.  After investigating, it turned out all colors are accurate, however there is NO hover interaction on tables after checking our neighboring resources and designs.  This is still an "active" state when something is selected however.
> style: remove hover color on tables

- framework/components/AInlineInputBase/AInlineInputBase.scss
> Prevent inline edit icon from shrinking when at the edge of a container

- framework/components/ADrawer/ADrawer.cy.js
- framework/components/ADrawer/ADrawer.js
- framework/components/ADrawer/ADrawer.mdx
- framework/components/ADrawer/ADrawer.scss
- framework/components/ADrawer/types.ts
- framework/components/ATriggerBase/ATriggerBase.tsx
-	[-] This change has been integrated and tested against 2 out of 3 typescript applications
-	[-] This change passed unit tests in these applications
-	[x] The changes are documented in component docs and changelog
-	[ ] The ESLint plugin has been updated if a new component is added
-	[x] Test have been added or modified, if appropriate
This adds a `size` prop to drawers. The value can either be a string
`type ADrawerSize = "sm" | "md" | "lg" | "xl"`
or an array containing any of those values.
If the value is a string, the drawer width will be set to the corresponding magnetic size width (vs specifying a width in pixels).
If the value is an array, the drawer width will default to (and be no smaller than) the size of the first value in …
> ADrawer specified responsive sizes

- framework/components/AFloatingBase/AFloatingBase.tsx
- framework/components/AFloatingBase/useFloatingBase.tsx
Ticket: https://cisco-sbg.atlassian.net/browse/XDR-16386
** NOTE **
I've only verified this in one Typescript app which is our Administration MFE on a development branch in `securex-ui-monorepo` via local linking. If you have another app I can test this against, please let me know.
> Fix: removed unused anchorRef in useFloatingBase

- .github/PULL_REQUEST_TEMPLATE.md
- framework/components/AActivityTimeline/AActivityTimeline.cy.js
- framework/components/AActivityTimeline/AActivityTimeline.js
- framework/components/AActivityTimeline/AActivityTimeline.mdx
- framework/components/AActivityTimeline/AActivityTimeline.scss
- framework/components/AActivityTimeline/AActivityTimelineItem.js
- framework/components/AActivityTimeline/types.ts
** #978 - Touch up activity timeline and add numbered lists**
**Numbered Pagination Lists**
CSS will only increment what is on the viewport as seen below in first image.  I was going to leave the option off for paginated lists since they can just add the number and override the styles, but that wouldn't have been very nice. This update also allows a developer to pass `numList` to `AActivityTimelineItem` if using a numbered paginated list to take advantage of same styling.
Before
After
> Feat/#978 timeline-updates

- framework/components/ATheme/ATheme.js
**Resolves #986 - React strict mode changes**
**Problem**
In react StrictMode, `useEffect`'s purposefully run twice to catch flakiness.  In this case, the theme was getting set properly, and then RESET with a bad state conflict of the newly set theme and the rerun of another "initial onload" set theme.
This check just ensures that we resave only when there's been a true onchange event.  This avoids the redundant reloads which cause the ripple effect of mismatching values which ultimately lead to a resetting of "default".
**To recreate issue in x__-components**
1) Go to `withAAppDecorator.jsx` and add:
``` jsx
const withAAppDecorator = (Story, props) => {
return (
<React.StrictMode>
<div style={{minWidth: "95%", height: "70vh"}}>
<AApp style={{height: "100%"}} persistTheme …
```
> fix: reduce useEffect call back to 1

- framework/components/APageLayout/APageAlert.d.ts
- framework/components/APageLayout/APageAlert.js
- framework/components/APageLayout/types.ts
When rendering `APageAlert` with React children in a TypeScript project, the following warning is shown:
This seems to be because of a combination of two things:
1. The prop types do not define `children`
2. There are no explicitly defined TypeScript types for the `APageAlert` props
Because of (2), I'm assuming something in this repo defaults to generating the TypeScript types from prop types. However, since `children` is missing in the prop types, the TypeScript type also excludes the `children` prop.
* Defines TypeScript types for the `APageAlert` component
* Adds `children` to the `APageAlert` prop types
> fix(APageAlert): refine prop types

- framework/components/ADrawer/ADrawer.js
Bugfix prompted by a discussion in UI dev channel.
The existing PropType definition for `ADrawers`s `responsiveWidth` is not quite correct. The Typescript type is correct, but if the build falls back to using proptypes, it may flag the issue.
> Bugfix ADrawer Responsive width array based prop type 

- framework/components/AActivityTimeline/AActivityTimeline.scss
When rendering `AActivityTimeline` with a single `AActivityTimelineItem` component, there is no space between the timeline's header and body:
Similarly, the last item in a list of timeline items doesn't render space between the header and body:
* Always adds padding between timeline item headers and body
* Done via `:has()` pseudo-class
1. Navigate to the Magna React docs site
2. Paste this into a sandbox:
```jsx
<AActivityTimeline>
<AActivityTimelineItem time="2022-02-12 21:11:10 UTC" title="Account Created">
You created your account. You can start playing!
</AActivityTimelineItem>
</AActivityTimeline>
```
3. **Verify that there is space between the timeline item header and body**
1. Navigate to the Magna React docs site
2. Paste this into a sandbox:
```jsx
<AActivityTimeline> …
```
> fix(AActivityTimeline): add space between header and body

- package-lock.json
- package.json
Updating from audit warnings
Severity: high
Next.js authorization bypass vulnerability - https://github.com/advisories/GHSA-7gfc-8cq8-jh5f
Next.js Allows a Denial of Service (DoS) with Server Actions - https://github.com/advisories/GHSA-7m27-7ghc-44w9
> deps: update next.js

- framework/components/APageLayout/APageAlert.js
- framework/components/APageLayout/types.ts
Although I fixed the `children` prop issue mentioned in https://github.com/cisco-sbg-ui/magna-react/pull/993, I forgot to add the props that are passed through to the `AToast` component:
* Has the `APageAlert` component extend the `AToast` component's props
N/A
> feat(APageAlert): add "AToast" props to types
